// GENERATED by packages/core/scripts/gen-data.mjs — do not edit by hand.
import type { Category } from "../types";
import type { RawLifecycle } from "../raw";

const data = {
  "grid": {
    "artifact": "atelo-phase-03-lifecycle-grid",
    "gate": "Gate 4 / L1",
    "environment": "bsc-testnet",
    "chainId": 97,
    "generatedAt": "2026-08-13T09:27:17.819Z",
    "keyMaterial": "none",
    "honesty": {
      "deliverableIsRealLabProposal": true,
      "deliverableSource": "labs/pancake-grid live QuoterV2 proposal from live pool slot0 (NOT the agent canned fixture)",
      "everyBroadcastSimulatedFirst": true,
      "chosenAgentIsFirstParty": true,
      "chosenAgentNote": "Atelo-owned reference agent (ERC-8004 agentId 1809), labeled first-party fallback; NOT third-party marketplace diversity"
    },
    "canonicalTask": {
      "network": "bsc-testnet",
      "wallet": "0xe8fb1F3329F1c9DD4d88aa666701f018CA5956ea",
      "objective": "execute a grid action within constraints",
      "agentBudget": "2000000000000000",
      "category": "grid",
      "protocol": "pancakeswap-v3",
      "constraints": {
        "maxSlippageBps": 30,
        "maxGasUsd": 3,
        "allowedContracts": [
          "0x1b81D678ffb9C0263b24A97847620C99d213eB14"
        ],
        "deadline": 2000000000
      }
    },
    "taskHash": "sha256:b9a798b5f636a01f2a24beed6bbe70711bef073840026e4c2fcdd3a55854ed6c",
    "spinePlan": {
      "chosenAgent": {
        "agentKey": "97-9001",
        "thirdParty": false,
        "firstPartyFallback": true,
        "score": 0.68,
        "label": "Atelo first-party reference agent (fallback — not third-party diversity)"
      },
      "action": {
        "category": "grid",
        "protocol": "pancakeswap-v3",
        "contract": "<TO_BE_FILLED_BY_LIVE_LAYER>",
        "method": "exactInputSingle",
        "argsSummary": {
          "tokenIn": "WBNB",
          "tokenOut": "USDT",
          "fee": 100,
          "amountIn": "2000000000000000",
          "direction": "SELL_WBNB",
          "gridLevels": 10,
          "maxSlippageBps": 30,
          "deadline": 2000000000
        },
        "requiresSignature": true,
        "simulatable": true
      },
      "liveActionContractResolved": "0x1b81D678ffb9C0263b24A97847620C99d213eB14",
      "liveActionContractNote": "spine action.contract is a placeholder resolved by the live layer to the pinned SwapRouter",
      "rankingContext": {
        "rankedAtBlock": 124812091,
        "scoreVersion": "atelo-rank/0",
        "sampleCount": 1,
        "windowNote": "query-time basic ranking over injected snapshots; first-party fallback performance is not counted as third-party diversity; full dynamic ranking epochs are Phase 5"
      },
      "rankedAtBlock": 124812091,
      "planActivityHash": "sha256:7c1937f015d041d6fa03985a859dc599b3a3d975b1b5e0f88932a0464517993b",
      "nextStep": "AWAIT_USER_SIGNATURE"
    },
    "realGridProposal": {
      "manifestHash": "sha256:c7ab8a254666910a932c1a86a7383e16de9b5fe31dff456a694cfa7507202cb6",
      "blockNumber": 124812091,
      "pool": "0xCed0844e421F856D2de472F9e7037f873987887C",
      "poolState": {
        "source": "on-chain",
        "currentTick": 187986,
        "fee": 100,
        "token0Label": "USDT",
        "token1Label": "WBNB",
        "midPriceUsdtPerWbnb": 6859.302116617272
      },
      "gridCount": 10,
      "levels": [
        6173.371904955545,
        6312.563996273372,
        6454.894475911832,
        6600.434105658881,
        6749.25524278083,
        6901.431875995874,
        7057.03966225872,
        7216.1559643746095,
        7378.859889461422,
        7545.232328278999
      ],
      "quotes": [
        {
          "source": "on-chain-quoterV2",
          "direction": "SELL_WBNB",
          "tokenIn": "WBNB",
          "tokenOut": "USDT",
          "tokenInAddress": "0xae13d989daC2f0dEbFf460aC112a837C89BAa7cd",
          "tokenOutAddress": "0xA11c8D9DC9b66E209Ef60F0C8D969D3CD988782c",
          "amountIn": "2000000000000000",
          "amountOut": "13682220",
          "execPriceUsdtPerWbnb": 6841.11,
          "levelIndex": 5,
          "levelPriceUsdtPerWbnb": 6901.431875995874,
          "note": "recommended signed leg: sell WBNB into USDT at an upper grid level"
        },
        {
          "source": "on-chain-quoterV2",
          "direction": "BUY_WBNB",
          "tokenIn": "USDT",
          "tokenOut": "WBNB",
          "tokenInAddress": "0xA11c8D9DC9b66E209Ef60F0C8D969D3CD988782c",
          "tokenOutAddress": "0xae13d989daC2f0dEbFf460aC112a837C89BAa7cd",
          "amountIn": "1000000",
          "amountOut": "145750779278396",
          "execPriceUsdtPerWbnb": 6861.026781132453,
          "levelIndex": 0,
          "levelPriceUsdtPerWbnb": 6173.371904955545,
          "note": "companion probe: buy WBNB with USDT at the lowest grid level"
        }
      ],
      "recommendedAction": {
        "protocol": "pancakeswap-v3",
        "target": "0x1b81D678ffb9C0263b24A97847620C99d213eB14",
        "functionName": "exactInputSingle",
        "direction": "SELL_WBNB",
        "tokenIn": "0xae13d989daC2f0dEbFf460aC112a837C89BAa7cd",
        "tokenOut": "0xA11c8D9DC9b66E209Ef60F0C8D969D3CD988782c",
        "fee": 100,
        "amountIn": "2000000000000000",
        "quotedAmountOut": "13682220"
      }
    },
    "erc8183Job": {
      "jobId": 501,
      "counterparty": {
        "name": "Atelo Reference Agent (Atelo-owned, not third-party)",
        "owner": "Atelo Hub",
        "third_party": false,
        "label": "reference",
        "erc8004_agent_id": 1809,
        "note": "Atelo-owned reference agent, NOT third-party diversity"
      },
      "endpoint": "https://models-practitioner-branches-regard.trycloudflare.com",
      "negotiate": {
        "endpoint": "https://models-practitioner-branches-regard.trycloudflare.com/erc8183/negotiate",
        "price_raw": "1000000000000000000",
        "currency": "0xc70B8741B8B07A6d61E54fd4B20f22Fa648E5565",
        "negotiation_hash": "0x2cdf16907bcff0f6ab8428c14ae6e911decbb62d4b25b3df77cc830439449e3c",
        "provider_sig_length": 132,
        "quote_expires_at": 1786612267,
        "third_party": false,
        "chain_id": 97
      },
      "policy": {
        "policy": "0xd6a4217588F6B1F5657a92A3e94E6422aD771cEA",
        "dispute_window_seconds": 900
      },
      "deliverable": {
        "deliverable_manifest_hash": "0x5a2e3666c9d87b9ac5332e3a3eb1a080e66f11fb1fab0ac5701b9ad8c40c3066",
        "deliverable_content_sha256": "c7ab8a254666910a932c1a86a7383e16de9b5fe31dff456a694cfa7507202cb6",
        "deliverable_bytes": 1951,
        "proposal_manifest_hash": "sha256:c7ab8a254666910a932c1a86a7383e16de9b5fe31dff456a694cfa7507202cb6",
        "grid_levels": 10,
        "recommended_action": {
          "protocol": "pancakeswap-v3",
          "target": "0x1b81D678ffb9C0263b24A97847620C99d213eB14",
          "functionName": "exactInputSingle",
          "direction": "SELL_WBNB",
          "tokenIn": "0xae13d989daC2f0dEbFf460aC112a837C89BAa7cd",
          "tokenOut": "0xA11c8D9DC9b66E209Ef60F0C8D969D3CD988782c",
          "fee": 100,
          "amountIn": "2000000000000000",
          "quotedAmountOut": "13682220"
        }
      },
      "onchainDeliverable": "0x5a2e3666c9d87b9ac5332e3a3eb1a080e66f11fb1fab0ac5701b9ad8c40c3066",
      "deliverableHashMatches": true,
      "settle": {
        "submitted_at": 1786612000,
        "dispute_window_seconds": 900,
        "settle_after": 1786612900,
        "actual_wait_seconds": 920,
        "verdict": "PENDING",
        "verdict_reason": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "final_status": "COMPLETED",
        "agent_payout": "1000000000000000000",
        "platform_fee_bp": 0,
        "protocol_fee_collected": "0",
        "payout_plus_fee_equals_budget": true
      },
      "settled": true,
      "finalBalances": {
        "client_token_balance": "0",
        "agent_token_balance": "7000000000000000000"
      },
      "transactions": [
        {
          "step": "create_job",
          "transactionHash": "0xe6a7a449a6a1c65c6e77d067151afdecadaa21228130f8d2ca93997d248220f2",
          "blockNumber": 124812451,
          "gasUsed": 625059,
          "effectiveGasPrice": 1000000000,
          "sponsored": false,
          "status": 1,
          "explorer": "https://testnet.bscscan.com/tx/0xe6a7a449a6a1c65c6e77d067151afdecadaa21228130f8d2ca93997d248220f2"
        },
        {
          "step": "register_job",
          "transactionHash": "0x2b93c8f104c80b95b4c87341702ac5701d6f4d0010aef5753702a9ee9f5d0904",
          "blockNumber": 124812459,
          "gasUsed": 135893,
          "effectiveGasPrice": 1000000000,
          "sponsored": false,
          "status": 1,
          "explorer": "https://testnet.bscscan.com/tx/0x2b93c8f104c80b95b4c87341702ac5701d6f4d0010aef5753702a9ee9f5d0904"
        },
        {
          "step": "set_budget",
          "transactionHash": "0xed74728f903303be19b54ce767b534e170bdc18db4991c94ce71cef0f41c270e",
          "blockNumber": 124812468,
          "gasUsed": 96162,
          "effectiveGasPrice": 1000000000,
          "sponsored": false,
          "status": 1,
          "explorer": "https://testnet.bscscan.com/tx/0xed74728f903303be19b54ce767b534e170bdc18db4991c94ce71cef0f41c270e"
        },
        {
          "step": "fund",
          "transactionHash": "0x27c9e482da54e60870aab0178e2cbf2e0eb33afebf4fc54494453528863a9967",
          "blockNumber": 124812489,
          "gasUsed": 97729,
          "effectiveGasPrice": 1000000000,
          "sponsored": false,
          "status": 1,
          "explorer": "https://testnet.bscscan.com/tx/0x27c9e482da54e60870aab0178e2cbf2e0eb33afebf4fc54494453528863a9967"
        },
        {
          "step": "submit",
          "transactionHash": "0x516f13ba3e3cdbc091e1814046f5338f5a31935e7a50c13d0bfab36457e26c67",
          "blockNumber": 124812505,
          "gasUsed": 197134,
          "effectiveGasPrice": 1000000000,
          "sponsored": false,
          "status": 1,
          "explorer": "https://testnet.bscscan.com/tx/0x516f13ba3e3cdbc091e1814046f5338f5a31935e7a50c13d0bfab36457e26c67"
        },
        {
          "step": "settle",
          "transactionHash": "0x4f8e475d9f89c20b713fd09db82fa43c832aca03e512d158b56da3c68e64c3ca",
          "blockNumber": 124814738,
          "gasUsed": 117631,
          "effectiveGasPrice": 1000000000,
          "sponsored": false,
          "status": 1,
          "explorer": "https://testnet.bscscan.com/tx/0x4f8e475d9f89c20b713fd09db82fa43c832aca03e512d158b56da3c68e64c3ca"
        }
      ],
      "blockRange": {
        "firstBlock": 124812451,
        "lastBlock": 124814738
      }
    },
    "signedProtocolAction": {
      "description": "user signs the proposed grid protocol action: real bounded exactInputSingle on the live pool",
      "pool": "0xCed0844e421F856D2de472F9e7037f873987887C",
      "contract": "0x1b81D678ffb9C0263b24A97847620C99d213eB14",
      "tokenIn": "0xae13d989daC2f0dEbFf460aC112a837C89BAa7cd",
      "tokenOut": "0xA11c8D9DC9b66E209Ef60F0C8D969D3CD988782c",
      "feeTier": 100,
      "swapTx": {
        "hash": "0x6368a27aac739f92b4804c5f11d3224f978de740a9bb521e21b5e84b362a2afb",
        "blockNumber": "124815147",
        "status": 1,
        "gasUsed": "133314",
        "effectiveGasPrice": "100000000",
        "gasCostWei": "13331400000000"
      },
      "wrapTx": null,
      "approveTx": {
        "hash": "0xdeedaec2a4416dba70189cc8872fb46663b668ef7ef5602462edc644f309fed5",
        "blockNumber": "124815131",
        "gasUsed": "46040",
        "effectiveGasPrice": "100000000",
        "status": 1
      },
      "amountInWBNB": "2000000000000000",
      "amountOutUSDT": "13682220",
      "quote": "13682220",
      "amountOutMinimum": "13545397",
      "execPrice": 6841.11,
      "execPriceUnit": "USDT per WBNB",
      "realizedSlippageBps": 0,
      "safety": {
        "s1SimulatedBeforeBroadcast": true,
        "s2SlippageBps": "100",
        "s2Deadline": "1786613787",
        "spendCeilingWei": "20000000000000000"
      }
    },
    "activityLedger": {
      "stages": [
        "TASK_SUBMITTED",
        "RANKED",
        "NEGOTIATED",
        "FUNDED",
        "RESULT_RECEIVED",
        "VALIDATED",
        "ACTION_SIGNED",
        "SETTLED",
        "RECORDED"
      ],
      "entries": [
        {
          "seq": 1,
          "atUtc": "2026-08-13T09:03:32.750Z",
          "stage": "TASK_SUBMITTED",
          "taskHash": "sha256:b9a798b5f636a01f2a24beed6bbe70711bef073840026e4c2fcdd3a55854ed6c",
          "detail": "canonical grid task on bsc-testnet"
        },
        {
          "seq": 2,
          "atUtc": "2026-08-13T09:03:32.750Z",
          "stage": "RANKED",
          "taskHash": "sha256:b9a798b5f636a01f2a24beed6bbe70711bef073840026e4c2fcdd3a55854ed6c",
          "agentKey": "97-9001",
          "detail": "chosen 97-9001 (first-party fallback) score 0.68 rankedAtBlock 124812091"
        },
        {
          "seq": 3,
          "atUtc": "2026-08-13T09:06:00.285575Z",
          "stage": "NEGOTIATED",
          "taskHash": "sha256:b9a798b5f636a01f2a24beed6bbe70711bef073840026e4c2fcdd3a55854ed6c",
          "agentKey": "97-9001",
          "detail": "ERC-8183 signed quote 0x2cdf16907bcff0f6ab8428c14ae6e911decbb62d4b25b3df77cc830439449e3c price 1000000000000000000 raw"
        },
        {
          "seq": 4,
          "atUtc": "2026-08-13T09:06:00.285575Z",
          "stage": "FUNDED",
          "taskHash": "sha256:b9a798b5f636a01f2a24beed6bbe70711bef073840026e4c2fcdd3a55854ed6c",
          "jobId": "501",
          "agentKey": "97-9001",
          "txHash": "0x27c9e482da54e60870aab0178e2cbf2e0eb33afebf4fc54494453528863a9967",
          "detail": "ERC-8183 escrow funded 1 U for job 501"
        },
        {
          "seq": 5,
          "atUtc": "2026-08-13T09:06:00.285575Z",
          "stage": "RESULT_RECEIVED",
          "taskHash": "sha256:b9a798b5f636a01f2a24beed6bbe70711bef073840026e4c2fcdd3a55854ed6c",
          "jobId": "501",
          "agentKey": "97-9001",
          "txHash": "0x516f13ba3e3cdbc091e1814046f5338f5a31935e7a50c13d0bfab36457e26c67",
          "detail": "real grid proposal delivered; onchain deliverable 0x5a2e3666c9d87b9ac5332e3a3eb1a080e66f11fb1fab0ac5701b9ad8c40c3066"
        },
        {
          "seq": 6,
          "atUtc": "2026-08-13T09:23:48.730629Z",
          "stage": "VALIDATED",
          "taskHash": "sha256:b9a798b5f636a01f2a24beed6bbe70711bef073840026e4c2fcdd3a55854ed6c",
          "jobId": "501",
          "agentKey": "97-9001",
          "detail": "action exactInputSingle simulatable=true; proposalManifestHash sha256:c7ab8a254666910a932c1a86a7383e16de9b5fe31dff456a694cfa7507202cb6"
        },
        {
          "seq": 7,
          "atUtc": "2026-08-13T09:26:31.077Z",
          "stage": "ACTION_SIGNED",
          "taskHash": "sha256:b9a798b5f636a01f2a24beed6bbe70711bef073840026e4c2fcdd3a55854ed6c",
          "jobId": "501",
          "agentKey": "97-9001",
          "txHash": "0x6368a27aac739f92b4804c5f11d3224f978de740a9bb521e21b5e84b362a2afb",
          "detail": "user signed exactInputSingle WBNB->USDT amountIn 2000000000000000 amountOut 13682220 realizedSlippageBps 0"
        },
        {
          "seq": 8,
          "atUtc": "2026-08-13T09:23:48.730629Z",
          "stage": "SETTLED",
          "taskHash": "sha256:b9a798b5f636a01f2a24beed6bbe70711bef073840026e4c2fcdd3a55854ed6c",
          "jobId": "501",
          "agentKey": "97-9001",
          "txHash": "0x4f8e475d9f89c20b713fd09db82fa43c832aca03e512d158b56da3c68e64c3ca",
          "detail": "job settled COMPLETED; provider payout 1000000000000000000 raw"
        },
        {
          "seq": 9,
          "atUtc": "2026-08-13T09:27:17.819Z",
          "stage": "RECORDED",
          "taskHash": "sha256:b9a798b5f636a01f2a24beed6bbe70711bef073840026e4c2fcdd3a55854ed6c",
          "jobId": "501",
          "agentKey": "97-9001",
          "detail": "full grid lifecycle recorded"
        }
      ],
      "activityHash": "sha256:1e1a329c68b3bbb46d4dd5fbd1c50496d6318ac965180c51a37aea4bf8fcdb1b"
    },
    "independentReVerification": {
      "jobStatus": "COMPLETED",
      "jobCompleted": true,
      "onchainDeliverable": "0x5a2e3666c9d87b9ac5332e3a3eb1a080e66f11fb1fab0ac5701b9ad8c40c3066",
      "swapTx": "0x6368a27aac739f92b4804c5f11d3224f978de740a9bb521e21b5e84b362a2afb",
      "swapBlock": 124815147,
      "swapStatus": 1,
      "swapStatusOk": true,
      "checkedBlock": 124815212
    },
    "gas": {
      "jobNativeWei": "1269608000000000",
      "swapLegNativeWei": "17935400000000",
      "totalNativeWei": "1287543400000000",
      "totalTbnb": 0.0012875434,
      "ceilingTbnb": 0.03
    },
    "reproduceCommands": [
      "cd labs/reference-agent && PORT=8003 REFERENCE_AGENT_HOST=127.0.0.1 PYTHONPATH=$PWD .venv/bin/python -m atelo_reference_agent",
      "cloudflared tunnel --url http://127.0.0.1:8003 ; set REFERENCE_AGENT_PUBLIC_URL in .env",
      "pnpm tsx labs/agent-probe/src/probe-cli.ts $REFERENCE_AGENT_PUBLIC_URL",
      "REFERENCE_AGENT_ID=1809 REFERENCE_AGENT_ALLOW_REGISTER=yes labs/reference-agent/.venv/bin/python labs/reference-agent/scripts/register.py --force --self-pay",
      "pnpm tsx labs/atelo-core/src/live-grid.ts",
      "REFERENCE_AGENT_ID=1809 labs/reference-agent/.venv/bin/python labs/reference-agent/scripts/live_grid_job.py --plan <live-grid.json> --out <grid-job.json>",
      "node --env-file=.env --import tsx labs/pancake-grid/src/live-swap.ts",
      "labs/reference-agent/.venv/bin/python labs/reference-agent/scripts/reverify.py --job-id <id> --swap-tx <hash> --out <reverify.json>",
      "pnpm tsx labs/atelo-core/src/assemble-evidence.ts"
    ],
    "manifestHash": "sha256:01493d6f70c4e57db5696d3a4f09357e44ce4b65b5ca5fd10e00094805ced568"
  },
  "rebalancing": {
    "artifact": "atelo-phase-03-lifecycle-rebalancing",
    "gate": "Gate 4 / L2",
    "environment": "bsc-testnet",
    "chainId": 97,
    "generatedAt": "2026-08-13T10:22:50.867Z",
    "keyMaterial": "none",
    "honesty": {
      "deliverableIsRealLabProposal": true,
      "deliverableSource": "labs pancake-rebalancing live on-chain proposal (NOT the agent canned /erc8183/task fixture)",
      "everyBroadcastSimulatedFirst": true,
      "chosenAgentIsFirstParty": true,
      "chosenAgentNote": "Atelo-owned reference agent (ERC-8004 agentId 1809), labeled first-party fallback; NOT third-party marketplace diversity"
    },
    "canonicalTask": {
      "network": "bsc-testnet",
      "wallet": "0xe8fb1F3329F1c9DD4d88aa666701f018CA5956ea",
      "objective": "execute a rebalancing action within constraints",
      "agentBudget": "2000000000000000",
      "category": "rebalancing",
      "protocol": "pancakeswap-v3",
      "positionId": "36813",
      "constraints": {
        "maxSlippageBps": 50,
        "maxGasUsd": 5,
        "allowedContracts": [
          "0x427bF5b37357632377eCbEC9de3626C71A5396c1"
        ],
        "deadline": 2000000000
      }
    },
    "taskHash": "sha256:59578b6bebad8ef6dd4674f81621d792511317442e0650c8659fdbfd7f28c362",
    "spinePlan": {
      "chosenAgent": {
        "agentKey": "97-9001",
        "thirdParty": false,
        "firstPartyFallback": true,
        "score": 0.68,
        "label": "Atelo first-party reference agent (fallback — not third-party diversity)"
      },
      "action": {
        "category": "rebalancing",
        "protocol": "pancakeswap-v3",
        "contract": "<TO_BE_FILLED_BY_LIVE_LAYER>",
        "method": "multicall(decreaseLiquidity,collect,mint)",
        "argsSummary": {
          "steps": [
            "decreaseLiquidity",
            "collect",
            "mint"
          ],
          "fee": 100,
          "pair": "USDT/WBNB",
          "proposedTickLower": 187986,
          "proposedTickUpper": 188086,
          "baseTick": 188036,
          "positionId": "36813"
        },
        "requiresSignature": true,
        "simulatable": true
      },
      "rankingContext": {
        "rankedAtBlock": 124818638,
        "scoreVersion": "atelo-rank/0",
        "sampleCount": 1,
        "windowNote": "query-time basic ranking over injected snapshots; first-party fallback performance is not counted as third-party diversity; full dynamic ranking epochs are Phase 5"
      },
      "rankedAtBlock": 124818638,
      "planActivityHash": "sha256:9728e94f1ae0f2e0cd4b573415306f648caf087e4bb36a8c5deb9a825a31255f",
      "nextStep": "AWAIT_USER_SIGNATURE"
    },
    "realProposal": {
      "manifestHash": "sha256:d1de8177ebf3de6157fe3a940435702473d24c401ef2d1a4065de0bf7c190aba",
      "lab": "pancake-rebalancing",
      "blockNumber": 124818638,
      "proposal": {
        "lab": "pancake-rebalancing",
        "kind": "real-live-rebalance-proposal",
        "environment": "bsc-testnet",
        "chainId": 97,
        "blockNumber": 124818638,
        "capturedUtc": "2026-08-13T09:52:39.152Z",
        "pool": "0xCed0844e421F856D2de472F9e7037f873987887C",
        "positionManager": "0x427bF5b37357632377eCbEC9de3626C71A5396c1",
        "positionId": "36813",
        "positionMode": "live-onchain",
        "poolState": {
          "source": "on-chain",
          "fee": 100,
          "tickSpacing": 1,
          "currentTick": 188036,
          "token0Label": "USDT",
          "token1Label": "WBNB",
          "midPriceUsdtPerWbnb": 6825.092910746241
        },
        "currentRange": {
          "tickLower": 187946,
          "tickUpper": 188046,
          "liquidity": "19317567437279",
          "inRange": true
        },
        "proposedRange": {
          "base": 188036,
          "lower": 187986,
          "upper": 188086
        },
        "recommendedAction": {
          "protocol": "pancakeswap-v3",
          "target": "0x427bF5b37357632377eCbEC9de3626C71A5396c1",
          "functionName": "multicall(decreaseLiquidity,collect,mint)",
          "positionId": "36813",
          "newTickLower": 187986,
          "newTickUpper": 188086
        },
        "dataNote": "current range + liquidity read live from NonfungiblePositionManager.positions(36813); proposed range recentered on live slot0 tick aligned to tickSpacing"
      }
    },
    "erc8183Job": {
      "jobId": 503,
      "counterparty": {
        "name": "Atelo Reference Agent (Atelo-owned, not third-party)",
        "owner": "Atelo Hub",
        "third_party": false,
        "label": "reference",
        "erc8004_agent_id": 1809,
        "note": "Atelo-owned reference agent, NOT third-party diversity"
      },
      "endpoint": "https://mileage-computing-caused-conservative.trycloudflare.com",
      "negotiate": {
        "endpoint": "https://mileage-computing-caused-conservative.trycloudflare.com/erc8183/negotiate",
        "price_raw": "1000000000000000000",
        "currency": "0xc70B8741B8B07A6d61E54fd4B20f22Fa648E5565",
        "negotiation_hash": "0xd775388bd25846038aaabbeb42aa9ce617dd3af9ab308bc1b0df5dbdcdef1285",
        "provider_sig_length": 132,
        "quote_expires_at": 1786615081,
        "third_party": false,
        "chain_id": 97
      },
      "policy": {
        "policy": "0xd6a4217588F6B1F5657a92A3e94E6422aD771cEA",
        "dispute_window_seconds": 900
      },
      "deliverable": {
        "deliverable_manifest_hash": "0xc1cb658271f910c4a36898accd02fd2670c1bc960c97d432b0973bc7a8268327",
        "deliverable_content_sha256": "d1de8177ebf3de6157fe3a940435702473d24c401ef2d1a4065de0bf7c190aba",
        "deliverable_bytes": 1058,
        "proposal_manifest_hash": "sha256:d1de8177ebf3de6157fe3a940435702473d24c401ef2d1a4065de0bf7c190aba",
        "summary": {
          "kind": "recommendedAction",
          "value": {
            "protocol": "pancakeswap-v3",
            "target": "0x427bF5b37357632377eCbEC9de3626C71A5396c1",
            "functionName": "multicall(decreaseLiquidity,collect,mint)",
            "positionId": "36813",
            "newTickLower": 187986,
            "newTickUpper": 188086
          }
        }
      },
      "onchainDeliverable": "0xc1cb658271f910c4a36898accd02fd2670c1bc960c97d432b0973bc7a8268327",
      "deliverableHashMatches": true,
      "settle": {
        "submitted_at": 1786614819,
        "dispute_window_seconds": 900,
        "settle_after": 1786615719,
        "actual_wait_seconds": 920,
        "verdict": "PENDING",
        "verdict_reason": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "final_status": "COMPLETED",
        "agent_payout": "1000000000000000000",
        "platform_fee_bp": 0,
        "protocol_fee_collected": "0",
        "payout_plus_fee_equals_budget": true
      },
      "settled": true,
      "finalBalances": {
        "client_token_balance": "2000000000000000000",
        "agent_token_balance": "8000000000000000000"
      },
      "transactions": [
        {
          "step": "create_job",
          "transactionHash": "0x4f99fadae04cd2396ab8f9581316acfa42a7414005587192ee7518731b123d3e",
          "blockNumber": 124818707,
          "gasUsed": 625215,
          "effectiveGasPrice": 1000000000,
          "sponsored": false,
          "status": 1,
          "explorer": "https://testnet.bscscan.com/tx/0x4f99fadae04cd2396ab8f9581316acfa42a7414005587192ee7518731b123d3e"
        },
        {
          "step": "register_job",
          "transactionHash": "0x55a9d3867d685f25915ff028954aa38fba02c9a318d8f5946e714edcd0b34264",
          "blockNumber": 124818716,
          "gasUsed": 135893,
          "effectiveGasPrice": 1000000000,
          "sponsored": false,
          "status": 1,
          "explorer": "https://testnet.bscscan.com/tx/0x55a9d3867d685f25915ff028954aa38fba02c9a318d8f5946e714edcd0b34264"
        },
        {
          "step": "set_budget",
          "transactionHash": "0x7ed68722d43c324ca2ea96d1cdc7977857e617dadb359359cbd5ad9b810f67dd",
          "blockNumber": 124818725,
          "gasUsed": 96162,
          "effectiveGasPrice": 1000000000,
          "sponsored": false,
          "status": 1,
          "explorer": "https://testnet.bscscan.com/tx/0x7ed68722d43c324ca2ea96d1cdc7977857e617dadb359359cbd5ad9b810f67dd"
        },
        {
          "step": "fund",
          "transactionHash": "0xdcb85d2473da3f9d10b294944b3b87b816f26b75b9473fdf8766fe6cf7765814",
          "blockNumber": 124818748,
          "gasUsed": 102529,
          "effectiveGasPrice": 1000000000,
          "sponsored": false,
          "status": 1,
          "explorer": "https://testnet.bscscan.com/tx/0xdcb85d2473da3f9d10b294944b3b87b816f26b75b9473fdf8766fe6cf7765814"
        },
        {
          "step": "submit",
          "transactionHash": "0x30a38cc53653c2e4f68cbc7bafe25b34fbe44c8d387b3bd28dda7d937187b82a",
          "blockNumber": 124818768,
          "gasUsed": 197741,
          "effectiveGasPrice": 1000000000,
          "sponsored": false,
          "status": 1,
          "explorer": "https://testnet.bscscan.com/tx/0x30a38cc53653c2e4f68cbc7bafe25b34fbe44c8d387b3bd28dda7d937187b82a"
        },
        {
          "step": "settle",
          "transactionHash": "0x44e76659b6237881bf6bf76d7ebb8b53a5032d8781611606b139ab0cc37fd0fe",
          "blockNumber": 124820837,
          "gasUsed": 117631,
          "effectiveGasPrice": 1000000000,
          "sponsored": false,
          "status": 1,
          "explorer": "https://testnet.bscscan.com/tx/0x44e76659b6237881bf6bf76d7ebb8b53a5032d8781611606b139ab0cc37fd0fe"
        }
      ],
      "blockRange": {
        "firstBlock": 124818707,
        "lastBlock": 124820837
      }
    },
    "signedProtocolAction": {
      "category": "rebalancing",
      "lab": "pancake-rebalancing",
      "kind": "signed live rebalance of existing position 36813 (decreaseLiquidity->collect->re-mint)",
      "environment": "bsc-testnet",
      "signedAction": true,
      "broadcast": true,
      "keyMaterial": "none",
      "resumeNote": "decreaseLiquidity broadcast+confirmed in the initial invocation (each step simulated before broadcast); a transient local DNS/RPC outage interrupted before the collect write was sent (no stuck nonce, collect never broadcast). This resume re-reads the confirmed decreaseLiquidity receipt and completes collect + re-mint, each simulated before broadcast.",
      "startedUtc": "2026-08-13T10:22:06.205Z",
      "chainId": 97,
      "startBlock": "124822561",
      "endBlock": "124822589",
      "pool": "0xCed0844e421F856D2de472F9e7037f873987887C",
      "deployer": "0xe8fb1F3329F1c9DD4d88aa666701f018CA5956ea",
      "positionManager": "0x427bF5b37357632377eCbEC9de3626C71A5396c1",
      "token0": "0xA11c8D9DC9b66E209Ef60F0C8D969D3CD988782c",
      "token1": "0xae13d989daC2f0dEbFf460aC112a837C89BAa7cd",
      "feeTier": 100,
      "tickSpacing": 1,
      "poolTickAtAction": 188036,
      "oldTokenId": "36813",
      "newTokenId": "36816",
      "oldRange": {
        "tickLower": 187946,
        "tickUpper": 188046
      },
      "newRange": {
        "tickLower": 187986,
        "tickUpper": 188086
      },
      "primaryTxHash": "0x421f0a84dd46610714bfa24db6d9faf7d1f3fc13e449a023393fe600ed8eba4e",
      "actionTxs": [
        {
          "step": "decreaseLiquidity",
          "hash": "0x3abcfbf4b797aec02849ddd35fa810ae111969ba276d2c965f7523ebaf150101",
          "blockNumber": "124820908",
          "status": 1,
          "gasUsed": "185491",
          "effectiveGasPrice": "100000000",
          "gasCostWei": "18549100000000"
        },
        {
          "step": "collect",
          "hash": "0xd3ab91a953e927c890803b5fcd795816f56f1f5c654648ddfcbd7c29f68b9b78",
          "blockNumber": "124822573",
          "status": 1,
          "gasUsed": "84374",
          "effectiveGasPrice": "100000000",
          "gasCostWei": "8437400000000"
        },
        {
          "step": "mint",
          "hash": "0x421f0a84dd46610714bfa24db6d9faf7d1f3fc13e449a023393fe600ed8eba4e",
          "blockNumber": "124822584",
          "status": 1,
          "gasUsed": "479836",
          "effectiveGasPrice": "100000000",
          "gasCostWei": "47983600000000"
        }
      ],
      "amounts": {
        "liquidityBefore": "19317567437279",
        "newLiquidity": "3619520074327",
        "decreasedAmount0": "734800",
        "decreasedAmount1": "1059031690455135",
        "collectedAmount0": "734800",
        "collectedAmount1": "1059071171741214",
        "feesCollected0": "0",
        "feesCollected1": "39481286079",
        "newAmount0": "734800",
        "newAmount1": "111115835128385"
      },
      "safety": {
        "s1SimulatedBeforeBroadcast": true,
        "s1SimulationFlags": {
          "decreaseLiquidity": true,
          "collect": true,
          "mint": true
        },
        "s2SlippageBps": "100",
        "spendCeilingWei": "20000000000000000",
        "cumulativeGasWei": "74970100000000"
      },
      "gasWei": "74970100000000",
      "totalTbnbSpentWei": "56421000000000",
      "verification": {
        "newPositionLiquidityPositive": true,
        "oldPositionDrained": true
      },
      "manifestHash": "sha256:a3bc394580d97c37952dd35c64a07ad8a2a96a2ced9bb131ff0eb521088560e6"
    },
    "activityLedger": {
      "stages": [
        "TASK_SUBMITTED",
        "RANKED",
        "NEGOTIATED",
        "FUNDED",
        "RESULT_RECEIVED",
        "VALIDATED",
        "ACTION_SIGNED",
        "SETTLED",
        "RECORDED"
      ],
      "entries": [
        {
          "seq": 1,
          "atUtc": "2026-08-13T09:52:39.152Z",
          "stage": "TASK_SUBMITTED",
          "taskHash": "sha256:59578b6bebad8ef6dd4674f81621d792511317442e0650c8659fdbfd7f28c362",
          "detail": "canonical rebalancing task on bsc-testnet"
        },
        {
          "seq": 2,
          "atUtc": "2026-08-13T09:52:39.152Z",
          "stage": "RANKED",
          "taskHash": "sha256:59578b6bebad8ef6dd4674f81621d792511317442e0650c8659fdbfd7f28c362",
          "agentKey": "97-9001",
          "detail": "chosen 97-9001 (first-party fallback) score 0.68 rankedAtBlock 124818638"
        },
        {
          "seq": 3,
          "atUtc": "2026-08-13T09:52:53.713188Z",
          "stage": "NEGOTIATED",
          "taskHash": "sha256:59578b6bebad8ef6dd4674f81621d792511317442e0650c8659fdbfd7f28c362",
          "agentKey": "97-9001",
          "detail": "ERC-8183 signed quote 0xd775388bd25846038aaabbeb42aa9ce617dd3af9ab308bc1b0df5dbdcdef1285 price 1000000000000000000 raw"
        },
        {
          "seq": 4,
          "atUtc": "2026-08-13T09:52:53.713188Z",
          "stage": "FUNDED",
          "taskHash": "sha256:59578b6bebad8ef6dd4674f81621d792511317442e0650c8659fdbfd7f28c362",
          "jobId": "503",
          "agentKey": "97-9001",
          "txHash": "0xdcb85d2473da3f9d10b294944b3b87b816f26b75b9473fdf8766fe6cf7765814",
          "detail": "ERC-8183 escrow funded 1 U for job 503"
        },
        {
          "seq": 5,
          "atUtc": "2026-08-13T09:52:53.713188Z",
          "stage": "RESULT_RECEIVED",
          "taskHash": "sha256:59578b6bebad8ef6dd4674f81621d792511317442e0650c8659fdbfd7f28c362",
          "jobId": "503",
          "agentKey": "97-9001",
          "txHash": "0x30a38cc53653c2e4f68cbc7bafe25b34fbe44c8d387b3bd28dda7d937187b82a",
          "detail": "real rebalancing proposal delivered; onchain deliverable 0xc1cb658271f910c4a36898accd02fd2670c1bc960c97d432b0973bc7a8268327"
        },
        {
          "seq": 6,
          "atUtc": "2026-08-13T10:09:15.258357Z",
          "stage": "VALIDATED",
          "taskHash": "sha256:59578b6bebad8ef6dd4674f81621d792511317442e0650c8659fdbfd7f28c362",
          "jobId": "503",
          "agentKey": "97-9001",
          "detail": "action multicall(decreaseLiquidity,collect,mint) simulatable=true; proposalManifestHash sha256:d1de8177ebf3de6157fe3a940435702473d24c401ef2d1a4065de0bf7c190aba"
        },
        {
          "seq": 7,
          "atUtc": "2026-08-13T10:22:06.205Z",
          "stage": "ACTION_SIGNED",
          "taskHash": "sha256:59578b6bebad8ef6dd4674f81621d792511317442e0650c8659fdbfd7f28c362",
          "jobId": "503",
          "agentKey": "97-9001",
          "txHash": "0x421f0a84dd46610714bfa24db6d9faf7d1f3fc13e449a023393fe600ed8eba4e",
          "detail": "user signed rebalance of position 36813 -> new position 36816 newRange [187986,188086] newLiquidity 3619520074327"
        },
        {
          "seq": 8,
          "atUtc": "2026-08-13T10:09:15.258357Z",
          "stage": "SETTLED",
          "taskHash": "sha256:59578b6bebad8ef6dd4674f81621d792511317442e0650c8659fdbfd7f28c362",
          "jobId": "503",
          "agentKey": "97-9001",
          "txHash": "0x44e76659b6237881bf6bf76d7ebb8b53a5032d8781611606b139ab0cc37fd0fe",
          "detail": "job settled COMPLETED; provider payout 1000000000000000000 raw"
        },
        {
          "seq": 9,
          "atUtc": "2026-08-13T10:22:50.867Z",
          "stage": "RECORDED",
          "taskHash": "sha256:59578b6bebad8ef6dd4674f81621d792511317442e0650c8659fdbfd7f28c362",
          "jobId": "503",
          "agentKey": "97-9001",
          "detail": "full rebalancing lifecycle recorded"
        }
      ],
      "activityHash": "sha256:f907dc6b2e1ded1033028fe9dce8ef1efa81b1f727adbcc086eed8162bdbd7ff"
    },
    "independentReVerification": {
      "jobStatus": "COMPLETED",
      "jobCompleted": true,
      "onchainDeliverable": "0xc1cb658271f910c4a36898accd02fd2670c1bc960c97d432b0973bc7a8268327",
      "actionTxs": [
        {
          "hash": "0x3abcfbf4b797aec02849ddd35fa810ae111969ba276d2c965f7523ebaf150101",
          "block": 124820908,
          "status": 1,
          "status_ok": true
        },
        {
          "hash": "0xd3ab91a953e927c890803b5fcd795816f56f1f5c654648ddfcbd7c29f68b9b78",
          "block": 124822573,
          "status": 1,
          "status_ok": true
        },
        {
          "hash": "0x421f0a84dd46610714bfa24db6d9faf7d1f3fc13e449a023393fe600ed8eba4e",
          "block": 124822584,
          "status": 1,
          "status_ok": true
        }
      ],
      "allActionsOk": true,
      "checkedBlock": 124822636
    },
    "gas": {
      "jobNativeWei": "1275171000000000",
      "actionNativeWei": "74970100000000",
      "totalNativeWei": "1350141100000000",
      "totalTbnb": 0.0013501411,
      "ceilingTbnb": 0.05
    },
    "reproduceCommands": [
      "cd labs/reference-agent && PORT=8003 REFERENCE_AGENT_HOST=127.0.0.1 PYTHONPATH=$PWD .venv/bin/python -m atelo_reference_agent",
      "cloudflared tunnel --url http://127.0.0.1:8003 ; set REFERENCE_AGENT_PUBLIC_URL in .env",
      "pnpm tsx labs/agent-probe/src/probe-cli.ts $REFERENCE_AGENT_PUBLIC_URL",
      "REFERENCE_AGENT_ID=1809 REFERENCE_AGENT_ALLOW_REGISTER=yes labs/reference-agent/.venv/bin/python labs/reference-agent/scripts/register.py --force --self-pay",
      "pnpm tsx labs/atelo-core/src/live-rebalancing-plan.ts",
      "REFERENCE_AGENT_ID=1809 labs/reference-agent/.venv/bin/python labs/reference-agent/scripts/live_category_job.py --category rebalancing --plan <plan.json> --out <job.json>",
      "node --env-file=.env --import tsx <category action script>",
      "labs/reference-agent/.venv/bin/python labs/reference-agent/scripts/reverify_action.py --job-id <id> --action-tx <hash> --out <reverify.json>",
      "pnpm tsx labs/atelo-core/src/assemble-lifecycle.ts"
    ],
    "manifestHash": "sha256:62ef9c3956b9b09127d4e1f60d4d495f001130607cbe9baaaa750f136e237254"
  },
  "yield": {
    "artifact": "atelo-phase-03-lifecycle-yield",
    "gate": "Gate 4 / L2",
    "environment": "bsc-testnet",
    "chainId": 97,
    "generatedAt": "2026-08-13T10:44:53.375Z",
    "keyMaterial": "none",
    "honesty": {
      "deliverableIsRealLabProposal": true,
      "deliverableSource": "labs pancake-yield live on-chain proposal (NOT the agent canned /erc8183/task fixture)",
      "everyBroadcastSimulatedFirst": true,
      "chosenAgentIsFirstParty": true,
      "chosenAgentNote": "Atelo-owned reference agent (ERC-8004 agentId 1809), labeled first-party fallback; NOT third-party marketplace diversity"
    },
    "canonicalTask": {
      "network": "bsc-testnet",
      "wallet": "0xe8fb1F3329F1c9DD4d88aa666701f018CA5956ea",
      "objective": "execute a yield action within constraints",
      "agentBudget": "2000000000000000",
      "category": "yield",
      "protocol": "pancakeswap-v3",
      "constraints": {
        "maxSlippageBps": 50,
        "maxGasUsd": 5,
        "allowedContracts": [
          "0x427bF5b37357632377eCbEC9de3626C71A5396c1"
        ],
        "deadline": 2000000000
      }
    },
    "taskHash": "sha256:49ca4b9d8577853e8523288df526f0a03b1f61fb5915c8f7415abda981303dc0",
    "spinePlan": {
      "chosenAgent": {
        "agentKey": "97-9001",
        "thirdParty": false,
        "firstPartyFallback": true,
        "score": 0.68,
        "label": "Atelo first-party reference agent (fallback — not third-party diversity)"
      },
      "action": {
        "category": "yield",
        "protocol": "pancakeswap-v3",
        "contract": "0x427bF5b37357632377eCbEC9de3626C71A5396c1",
        "method": "mint",
        "argsSummary": {
          "token0": "0xA11c8D9DC9b66E209Ef60F0C8D969D3CD988782c",
          "token1": "0xae13d989daC2f0dEbFf460aC112a837C89BAa7cd",
          "fee": 100,
          "tickLower": 187986,
          "tickUpper": 188086,
          "amount0Desired": "1000000",
          "amount1Desired": "1000000000000000",
          "deadline": 2000000000
        },
        "requiresSignature": true,
        "simulatable": true
      },
      "rankingContext": {
        "rankedAtBlock": 124822709,
        "scoreVersion": "atelo-rank/0",
        "sampleCount": 1,
        "windowNote": "query-time basic ranking over injected snapshots; first-party fallback performance is not counted as third-party diversity; full dynamic ranking epochs are Phase 5"
      },
      "rankedAtBlock": 124822709,
      "planActivityHash": "sha256:eafcf5f12f49dc5ced5e40bc4e93e284cc9b775cc95569e62f05ae356835c916",
      "nextStep": "AWAIT_USER_SIGNATURE"
    },
    "realProposal": {
      "manifestHash": "sha256:d7755ac72d14e15372e375db8be2418fca32c2b3981fe6701ae1e3d799b6f3ba",
      "lab": "pancake-yield",
      "blockNumber": 124822709,
      "proposal": {
        "lab": "pancake-yield",
        "kind": "real-live-yield-proposal",
        "environment": "bsc-testnet",
        "chainId": 97,
        "blockNumber": 124822709,
        "capturedUtc": "2026-08-13T10:23:11.444Z",
        "pair": "WBNB/USDT",
        "feeTiersCompared": [
          100,
          500
        ],
        "primaryPool": "0xCed0844e421F856D2de472F9e7037f873987887C",
        "poolState": {
          "source": "on-chain",
          "fee": 100,
          "currentTick": 188036,
          "token0Label": "USDT",
          "token1Label": "WBNB",
          "liquidity": "49866028522871",
          "hasLiquidity": true,
          "tvlUsdt": 4026.9430920896916,
          "midPriceUsdtPerWbnb": 6825.092910746241
        },
        "recommendation": {
          "choice": "WBNB/USDT 100",
          "reason": "the 0.01% pool is the only WBNB/USDT tier with non-zero live liquidity and real TVL; a concentrated position around spot is the recommended yield deposit",
          "advertisedVsRealized": "realized APR is unmeasurable via view calls on testnet; deposit is opened to hold a live concentrated position"
        },
        "depositPlan": {
          "functionName": "mint",
          "target": "0x427bF5b37357632377eCbEC9de3626C71A5396c1",
          "params": {
            "token0": "0xA11c8D9DC9b66E209Ef60F0C8D969D3CD988782c",
            "token1": "0xae13d989daC2f0dEbFf460aC112a837C89BAa7cd",
            "fee": 100,
            "tickLower": 187986,
            "tickUpper": 188086,
            "amount0Desired": "1000000",
            "amount1Desired": "1000000000000000",
            "amount0Min": "0",
            "amount1Min": "0"
          }
        },
        "dataNote": "pool discovered via PancakeV3Factory.getPool(WBNB,USDT,100); tick/liquidity/TVL read live; proposed symmetric range centered on live slot0 tick"
      }
    },
    "erc8183Job": {
      "jobId": 504,
      "counterparty": {
        "name": "Atelo Reference Agent (Atelo-owned, not third-party)",
        "owner": "Atelo Hub",
        "third_party": false,
        "label": "reference",
        "erc8004_agent_id": 1809,
        "note": "Atelo-owned reference agent, NOT third-party diversity"
      },
      "endpoint": "https://mileage-computing-caused-conservative.trycloudflare.com",
      "negotiate": {
        "negotiation_hash": "0xbdfac255615164c4af02342374abef9812e2f30f1ed81f27ebeee9e421b64a6c",
        "price_raw": "1000000000000000000",
        "currency": "0xc70B8741B8B07A6d61E54fd4B20f22Fa648E5565",
        "source": "recovered from on-chain create_job description",
        "third_party": false,
        "chain_id": 97
      },
      "policy": {
        "policy": "0xd6a4217588F6B1F5657a92A3e94E6422aD771cEA",
        "dispute_window_seconds": 900
      },
      "deliverable": {
        "deliverable_manifest_hash": "0x23e09e5365f4b2e07d8eb440a640d6d3d18cceeff2206d4347ee9865afb8800e",
        "deliverable_content_sha256": "d7755ac72d14e15372e375db8be2418fca32c2b3981fe6701ae1e3d799b6f3ba",
        "deliverable_bytes": 1353,
        "proposal_manifest_hash": "sha256:d7755ac72d14e15372e375db8be2418fca32c2b3981fe6701ae1e3d799b6f3ba",
        "summary": {
          "kind": "depositPlan",
          "value": {
            "functionName": "mint",
            "target": "0x427bF5b37357632377eCbEC9de3626C71A5396c1",
            "params": {
              "token0": "0xA11c8D9DC9b66E209Ef60F0C8D969D3CD988782c",
              "token1": "0xae13d989daC2f0dEbFf460aC112a837C89BAa7cd",
              "fee": 100,
              "tickLower": 187986,
              "tickUpper": 188086,
              "amount0Desired": "1000000",
              "amount1Desired": "1000000000000000",
              "amount0Min": "0",
              "amount1Min": "0"
            }
          }
        }
      },
      "onchainDeliverable": "0x23e09e5365f4b2e07d8eb440a640d6d3d18cceeff2206d4347ee9865afb8800e",
      "deliverableHashMatches": true,
      "settle": {
        "submitted_at": 1786616655,
        "dispute_window_seconds": 900,
        "verdict": "PENDING",
        "final_status": "COMPLETED",
        "agent_payout": "1000000000000000000",
        "platform_fee_bp": 0,
        "protocol_fee_collected": "0",
        "payout_plus_fee_equals_budget": true
      },
      "settled": true,
      "finalBalances": {
        "client_token_balance": "1000000000000000000",
        "agent_token_balance": "9000000000000000000"
      },
      "transactions": [
        {
          "step": "create_job",
          "transactionHash": "0x730c567cfba19d0de5c8ed8a9ee96c89988171a6b76be29973fa4b3d4a774add",
          "blockNumber": 124822787,
          "gasUsed": 625155,
          "effectiveGasPrice": 1000000000,
          "sponsored": false,
          "status": 1,
          "explorer": "https://testnet.bscscan.com/tx/0x730c567cfba19d0de5c8ed8a9ee96c89988171a6b76be29973fa4b3d4a774add"
        },
        {
          "step": "register_job",
          "transactionHash": "0x44894c5c73ba8c4116adeaa319f4bfbcdd0bfbe4c72629753c775d5f5bb31bb6",
          "blockNumber": 124822800,
          "gasUsed": 135893,
          "effectiveGasPrice": 1000000000,
          "sponsored": false,
          "status": 1,
          "explorer": "https://testnet.bscscan.com/tx/0x44894c5c73ba8c4116adeaa319f4bfbcdd0bfbe4c72629753c775d5f5bb31bb6"
        },
        {
          "step": "set_budget",
          "transactionHash": "0xafcba770fc1debe546fa2cef18505a4931b4e8a57469906acfbb596d9232a25c",
          "blockNumber": 124822809,
          "gasUsed": 96162,
          "effectiveGasPrice": 1000000000,
          "sponsored": false,
          "status": 1,
          "explorer": "https://testnet.bscscan.com/tx/0xafcba770fc1debe546fa2cef18505a4931b4e8a57469906acfbb596d9232a25c"
        },
        {
          "step": "fund",
          "transactionHash": "0xaf4f0b586006530bd2e4934d17cf24ea961027cb1c3afd1c39aa96c669c9b46b",
          "blockNumber": 124822830,
          "gasUsed": 102529,
          "effectiveGasPrice": 1000000000,
          "sponsored": false,
          "status": 1,
          "explorer": "https://testnet.bscscan.com/tx/0xaf4f0b586006530bd2e4934d17cf24ea961027cb1c3afd1c39aa96c669c9b46b"
        },
        {
          "step": "submit",
          "transactionHash": "0xab31fa83772bad3228079ba48446bb9604758efaadd14ca8a6a4c9f129f739e7",
          "blockNumber": 124822849,
          "gasUsed": 197158,
          "effectiveGasPrice": 1000000000,
          "sponsored": false,
          "status": 1,
          "explorer": "https://testnet.bscscan.com/tx/0xab31fa83772bad3228079ba48446bb9604758efaadd14ca8a6a4c9f129f739e7"
        },
        {
          "step": "settle",
          "transactionHash": "0x12cafe9ed038a207ffb609526cddf7fed7795c50c6a743f6cbf5c6981f177bd9",
          "blockNumber": 124824903,
          "gasUsed": 117631,
          "effectiveGasPrice": 1000000000,
          "sponsored": false,
          "status": 1,
          "explorer": "https://testnet.bscscan.com/tx/0x12cafe9ed038a207ffb609526cddf7fed7795c50c6a743f6cbf5c6981f177bd9"
        }
      ],
      "blockRange": {
        "firstBlock": 124822787,
        "lastBlock": 124824903
      }
    },
    "signedProtocolAction": {
      "category": "yield",
      "lab": "pancake-yield",
      "kind": "signed live yield deposit (NPM.mint concentrated position)",
      "environment": "bsc-testnet",
      "signedAction": true,
      "broadcast": true,
      "keyMaterial": "none",
      "startedUtc": "2026-08-13T10:44:25.429Z",
      "chainId": 97,
      "startBlock": "124825537",
      "endBlock": "124825546",
      "deployer": "0xe8fb1F3329F1c9DD4d88aa666701f018CA5956ea",
      "positionManager": "0x427bF5b37357632377eCbEC9de3626C71A5396c1",
      "token0": "0xA11c8D9DC9b66E209Ef60F0C8D969D3CD988782c",
      "token1": "0xae13d989daC2f0dEbFf460aC112a837C89BAa7cd",
      "feeTier": 100,
      "range": {
        "tickLower": 187986,
        "tickUpper": 188086
      },
      "newTokenId": "36818",
      "primaryTxHash": "0x0a53c350f78aa019a3637d2476e3fcdf33a23a09dc356110f6e060e681dc1570",
      "actionTxs": [
        {
          "step": "mint",
          "hash": "0x0a53c350f78aa019a3637d2476e3fcdf33a23a09dc356110f6e060e681dc1570",
          "blockNumber": "124825547",
          "status": 1,
          "gasUsed": "320549",
          "effectiveGasPrice": "100000000",
          "gasCostWei": "32054900000000"
        }
      ],
      "amounts": {
        "amount0Desired": "1000000",
        "amount1Desired": "1000000000000000",
        "usedAmount0Usdt": "1000000",
        "usedAmount1Wbnb": "151219155046780",
        "newLiquidity": "4925857477309"
      },
      "safety": {
        "s1SimulatedBeforeBroadcast": true,
        "s1SimulationFlags": {
          "mint": true
        },
        "s2SlippageBps": "100",
        "spendCeilingWei": "20000000000000000",
        "cumulativeGasWei": "32054900000000"
      },
      "gasWei": "32054900000000",
      "totalTbnbSpentWei": "32054900000000",
      "verification": {
        "newPositionLiquidityPositive": true
      },
      "manifestHash": "sha256:57b8f4fb8912f3274620f70ffcf430456d298d56be325ffdc60c4f218fae21fa"
    },
    "activityLedger": {
      "stages": [
        "TASK_SUBMITTED",
        "RANKED",
        "NEGOTIATED",
        "FUNDED",
        "RESULT_RECEIVED",
        "VALIDATED",
        "ACTION_SIGNED",
        "SETTLED",
        "RECORDED"
      ],
      "entries": [
        {
          "seq": 1,
          "atUtc": "2026-08-13T10:23:11.444Z",
          "stage": "TASK_SUBMITTED",
          "taskHash": "sha256:49ca4b9d8577853e8523288df526f0a03b1f61fb5915c8f7415abda981303dc0",
          "detail": "canonical yield task on bsc-testnet"
        },
        {
          "seq": 2,
          "atUtc": "2026-08-13T10:23:11.444Z",
          "stage": "RANKED",
          "taskHash": "sha256:49ca4b9d8577853e8523288df526f0a03b1f61fb5915c8f7415abda981303dc0",
          "agentKey": "97-9001",
          "detail": "chosen 97-9001 (first-party fallback) score 0.68 rankedAtBlock 124822709"
        },
        {
          "seq": 3,
          "atUtc": "2026-08-13T10:23:47Z",
          "stage": "NEGOTIATED",
          "taskHash": "sha256:49ca4b9d8577853e8523288df526f0a03b1f61fb5915c8f7415abda981303dc0",
          "agentKey": "97-9001",
          "detail": "ERC-8183 signed quote 0xbdfac255615164c4af02342374abef9812e2f30f1ed81f27ebeee9e421b64a6c price 1000000000000000000 raw"
        },
        {
          "seq": 4,
          "atUtc": "2026-08-13T10:23:47Z",
          "stage": "FUNDED",
          "taskHash": "sha256:49ca4b9d8577853e8523288df526f0a03b1f61fb5915c8f7415abda981303dc0",
          "jobId": "504",
          "agentKey": "97-9001",
          "txHash": "0xaf4f0b586006530bd2e4934d17cf24ea961027cb1c3afd1c39aa96c669c9b46b",
          "detail": "ERC-8183 escrow funded 1 U for job 504"
        },
        {
          "seq": 5,
          "atUtc": "2026-08-13T10:23:47Z",
          "stage": "RESULT_RECEIVED",
          "taskHash": "sha256:49ca4b9d8577853e8523288df526f0a03b1f61fb5915c8f7415abda981303dc0",
          "jobId": "504",
          "agentKey": "97-9001",
          "txHash": "0xab31fa83772bad3228079ba48446bb9604758efaadd14ca8a6a4c9f129f739e7",
          "detail": "real yield proposal delivered; onchain deliverable 0x23e09e5365f4b2e07d8eb440a640d6d3d18cceeff2206d4347ee9865afb8800e"
        },
        {
          "seq": 6,
          "atUtc": "2026-08-13T10:44:06.713185Z",
          "stage": "VALIDATED",
          "taskHash": "sha256:49ca4b9d8577853e8523288df526f0a03b1f61fb5915c8f7415abda981303dc0",
          "jobId": "504",
          "agentKey": "97-9001",
          "detail": "action mint simulatable=true; proposalManifestHash sha256:d7755ac72d14e15372e375db8be2418fca32c2b3981fe6701ae1e3d799b6f3ba"
        },
        {
          "seq": 7,
          "atUtc": "2026-08-13T10:44:25.429Z",
          "stage": "ACTION_SIGNED",
          "taskHash": "sha256:49ca4b9d8577853e8523288df526f0a03b1f61fb5915c8f7415abda981303dc0",
          "jobId": "504",
          "agentKey": "97-9001",
          "txHash": "0x0a53c350f78aa019a3637d2476e3fcdf33a23a09dc356110f6e060e681dc1570",
          "detail": "user signed NPM.mint yield deposit tokenId 36818 usedUSDT 1000000 usedWBNB 151219155046780 liquidity 4925857477309"
        },
        {
          "seq": 8,
          "atUtc": "2026-08-13T10:44:06.713185Z",
          "stage": "SETTLED",
          "taskHash": "sha256:49ca4b9d8577853e8523288df526f0a03b1f61fb5915c8f7415abda981303dc0",
          "jobId": "504",
          "agentKey": "97-9001",
          "txHash": "0x12cafe9ed038a207ffb609526cddf7fed7795c50c6a743f6cbf5c6981f177bd9",
          "detail": "job settled COMPLETED; provider payout 1000000000000000000 raw"
        },
        {
          "seq": 9,
          "atUtc": "2026-08-13T10:44:53.375Z",
          "stage": "RECORDED",
          "taskHash": "sha256:49ca4b9d8577853e8523288df526f0a03b1f61fb5915c8f7415abda981303dc0",
          "jobId": "504",
          "agentKey": "97-9001",
          "detail": "full yield lifecycle recorded"
        }
      ],
      "activityHash": "sha256:0c0caf31914ade657c6abd388a61727c42be7a939700a33cca0b0af2a8ffd640"
    },
    "independentReVerification": {
      "jobStatus": "COMPLETED",
      "jobCompleted": true,
      "onchainDeliverable": "0x23e09e5365f4b2e07d8eb440a640d6d3d18cceeff2206d4347ee9865afb8800e",
      "actionTxs": [
        {
          "hash": "0x0a53c350f78aa019a3637d2476e3fcdf33a23a09dc356110f6e060e681dc1570",
          "block": 124825547,
          "status": 1,
          "status_ok": true
        }
      ],
      "allActionsOk": true,
      "checkedBlock": 124825598
    },
    "gas": {
      "jobNativeWei": "1274528000000000",
      "actionNativeWei": "32054900000000",
      "totalNativeWei": "1306582900000000",
      "totalTbnb": 0.0013065829,
      "ceilingTbnb": 0.05
    },
    "reproduceCommands": [
      "cd labs/reference-agent && PORT=8003 REFERENCE_AGENT_HOST=127.0.0.1 PYTHONPATH=$PWD .venv/bin/python -m atelo_reference_agent",
      "cloudflared tunnel --url http://127.0.0.1:8003 ; set REFERENCE_AGENT_PUBLIC_URL in .env",
      "pnpm tsx labs/agent-probe/src/probe-cli.ts $REFERENCE_AGENT_PUBLIC_URL",
      "REFERENCE_AGENT_ID=1809 REFERENCE_AGENT_ALLOW_REGISTER=yes labs/reference-agent/.venv/bin/python labs/reference-agent/scripts/register.py --force --self-pay",
      "pnpm tsx labs/atelo-core/src/live-yield-plan.ts",
      "REFERENCE_AGENT_ID=1809 labs/reference-agent/.venv/bin/python labs/reference-agent/scripts/live_category_job.py --category yield --plan <plan.json> --out <job.json>",
      "node --env-file=.env --import tsx <category action script>",
      "labs/reference-agent/.venv/bin/python labs/reference-agent/scripts/reverify_action.py --job-id <id> --action-tx <hash> --out <reverify.json>",
      "pnpm tsx labs/atelo-core/src/assemble-lifecycle.ts"
    ],
    "manifestHash": "sha256:ab51f15d8782c175c703dff94ac31e16a3ed9d5c5c820cb63cb8b95634fc6fbf"
  },
  "health": {
    "artifact": "atelo-phase-03-lifecycle-venus",
    "gate": "Gate 4 / L2",
    "environment": "bsc-testnet",
    "chainId": 97,
    "generatedAt": "2026-08-13T11:04:16.633Z",
    "keyMaterial": "none",
    "honesty": {
      "deliverableIsRealLabProposal": true,
      "deliverableSource": "labs venus-health live on-chain proposal (NOT the agent canned /erc8183/task fixture)",
      "everyBroadcastSimulatedFirst": true,
      "chosenAgentIsFirstParty": true,
      "chosenAgentNote": "Atelo-owned reference agent (ERC-8004 agentId 1809), labeled first-party fallback; NOT third-party marketplace diversity"
    },
    "canonicalTask": {
      "network": "bsc-testnet",
      "wallet": "0xe8fb1F3329F1c9DD4d88aa666701f018CA5956ea",
      "objective": "execute a health action within constraints",
      "agentBudget": "2000000000000000",
      "category": "health",
      "protocol": "venus",
      "constraints": {
        "maxSlippageBps": 0,
        "maxGasUsd": 3,
        "allowedContracts": [
          "0xb7526572FFE56AB9D7489838Bf2E18e3323b441A"
        ],
        "deadline": 2000000000
      }
    },
    "taskHash": "sha256:700ed2bcf6423a57e80a73ffec2b851b478f51b72240112811c1ef0b5cd0ac2b",
    "spinePlan": {
      "chosenAgent": {
        "agentKey": "97-9001",
        "thirdParty": false,
        "firstPartyFallback": true,
        "score": 0.68,
        "label": "Atelo first-party reference agent (fallback — not third-party diversity)"
      },
      "action": {
        "category": "health",
        "protocol": "venus",
        "contract": "0xb7526572FFE56AB9D7489838Bf2E18e3323b441A",
        "method": "repayBorrow",
        "argsSummary": {
          "vTokenAction": "repayBorrow",
          "market": "vUSDT",
          "underlying": "USDT",
          "amountBaseUnits": "500000",
          "healthFactor": 7.49999925,
          "healthFactorLabel": "7.499999"
        },
        "requiresSignature": true,
        "simulatable": true
      },
      "rankingContext": {
        "rankedAtBlock": 124825683,
        "scoreVersion": "atelo-rank/0",
        "sampleCount": 1,
        "windowNote": "query-time basic ranking over injected snapshots; first-party fallback performance is not counted as third-party diversity; full dynamic ranking epochs are Phase 5"
      },
      "rankedAtBlock": 124825683,
      "planActivityHash": "sha256:9f50ad6698455ddd6ebae00613c8a20d752488363e1f6c299a2b5d5ef1570ebd",
      "nextStep": "AWAIT_USER_SIGNATURE"
    },
    "realProposal": {
      "manifestHash": "sha256:63fd2a503cc4006aa091952b8d5c03c5d409a18c6ca250994633fb7eab192391",
      "lab": "venus-health",
      "blockNumber": 124825683,
      "proposal": {
        "lab": "venus-health",
        "kind": "real-live-health-proposal",
        "environment": "bsc-testnet",
        "chainId": 97,
        "blockNumber": 124825683,
        "capturedUtc": "2026-08-13T10:45:29.904Z",
        "comptroller": "0x94d1820b2D1c7c7452A163983Dc888CEC546b77D",
        "oracle": "0x3cD69251D04A28d887Ac14cbe2E14c52F3D57823",
        "account": "0xe8fb1F3329F1c9DD4d88aa666701f018CA5956ea",
        "healthFactor": 7.49999925,
        "healthFactorLabel": "7.499999",
        "collateralUsd": "4.9999995",
        "weightedCollateralUsd": "3.749999625",
        "borrowUsd": "0.5",
        "accountLiquidityUsd": "3.499999999907899081",
        "shortfallUsd": "0",
        "perMarket": [
          {
            "label": "vUSDT",
            "vToken": "0xb7526572FFE56AB9D7489838Bf2E18e3323b441A",
            "underlyingLabel": "USDT",
            "underlyingDecimals": 6,
            "vTokenBalance": "49806635218",
            "borrowBalance": "1000000",
            "exchangeRate": "200776461931237",
            "collateralFactorMantissa": "750000000000000000",
            "priceMantissa": "500000000000000000000000000000",
            "oracleImpliedUsd": 0.5,
            "supplyUnderlying": "9999999",
            "supplyUsd": "4.9999995",
            "weightedCollateralUsd": "3.749999625",
            "borrowUsd": "0.5"
          }
        ],
        "currentBorrowBaseUnits": "1000000",
        "actions": [
          {
            "kind": "repayBorrow",
            "market": "vUSDT",
            "underlyingLabel": "USDT",
            "amountBaseUnits": "500000",
            "to": "0xb7526572FFE56AB9D7489838Bf2E18e3323b441A",
            "note": "corrective partial repay of the live vUSDT debt; cuts borrow and raises health factor while leaving a live position"
          }
        ],
        "dataNote": "health factor and per-market metrics computed from live Comptroller/oracle reads on the deployer account; recommended repay sized against the live borrow balance"
      }
    },
    "erc8183Job": {
      "jobId": 505,
      "counterparty": {
        "name": "Atelo Reference Agent (Atelo-owned, not third-party)",
        "owner": "Atelo Hub",
        "third_party": false,
        "label": "reference",
        "erc8004_agent_id": 1809,
        "note": "Atelo-owned reference agent, NOT third-party diversity"
      },
      "endpoint": "https://mileage-computing-caused-conservative.trycloudflare.com",
      "negotiate": {
        "negotiation_hash": "0x3fa8ef1fbdd03117ae26301195874b7279288d32e8db48ecd78823abbdc83844",
        "price_raw": "1000000000000000000",
        "currency": "0xc70B8741B8B07A6d61E54fd4B20f22Fa648E5565",
        "source": "recovered from on-chain create_job description",
        "third_party": false,
        "chain_id": 97
      },
      "policy": {
        "policy": "0xd6a4217588F6B1F5657a92A3e94E6422aD771cEA",
        "dispute_window_seconds": 900
      },
      "deliverable": {
        "deliverable_manifest_hash": "0x8720b058c395120077d2806f28edc7d09218752fd7163b229d4edaaafd923631",
        "deliverable_content_sha256": "63fd2a503cc4006aa091952b8d5c03c5d409a18c6ca250994633fb7eab192391",
        "deliverable_bytes": 1477,
        "proposal_manifest_hash": "sha256:63fd2a503cc4006aa091952b8d5c03c5d409a18c6ca250994633fb7eab192391",
        "summary": {
          "kind": "actions",
          "value": {
            "kind": "repayBorrow",
            "market": "vUSDT",
            "underlyingLabel": "USDT",
            "amountBaseUnits": "500000",
            "to": "0xb7526572FFE56AB9D7489838Bf2E18e3323b441A",
            "note": "corrective partial repay of the live vUSDT debt; cuts borrow and raises health factor while leaving a live position"
          }
        }
      },
      "onchainDeliverable": "0x8720b058c395120077d2806f28edc7d09218752fd7163b229d4edaaafd923631",
      "deliverableHashMatches": true,
      "settle": {
        "submitted_at": 1786617994,
        "dispute_window_seconds": 900,
        "verdict": "PENDING",
        "final_status": "COMPLETED",
        "agent_payout": "1000000000000000000",
        "platform_fee_bp": 0,
        "protocol_fee_collected": "0",
        "payout_plus_fee_equals_budget": true
      },
      "settled": true,
      "finalBalances": {
        "client_token_balance": "0",
        "agent_token_balance": "10000000000000000000"
      },
      "transactions": [
        {
          "step": "create_job",
          "transactionHash": "0x5b904752737146125b978eb4e122fef316f52bbec9dbe3055e481683ab50fcf4",
          "blockNumber": 124825764,
          "gasUsed": 625252,
          "effectiveGasPrice": 1000000000,
          "sponsored": false,
          "status": 1,
          "explorer": "https://testnet.bscscan.com/tx/0x5b904752737146125b978eb4e122fef316f52bbec9dbe3055e481683ab50fcf4"
        },
        {
          "step": "register_job",
          "transactionHash": "0x1cc3de4bae32c1e865922e731247db937c3b10bb4d7f891d8656069e54508f93",
          "blockNumber": 124825772,
          "gasUsed": 135893,
          "effectiveGasPrice": 1000000000,
          "sponsored": false,
          "status": 1,
          "explorer": "https://testnet.bscscan.com/tx/0x1cc3de4bae32c1e865922e731247db937c3b10bb4d7f891d8656069e54508f93"
        },
        {
          "step": "set_budget",
          "transactionHash": "0xa9f4ce5675aa9fbfe0414d4ac9d3179bbedbc3743b84bc340ed74f119bf0bf41",
          "blockNumber": 124825780,
          "gasUsed": 96162,
          "effectiveGasPrice": 1000000000,
          "sponsored": false,
          "status": 1,
          "explorer": "https://testnet.bscscan.com/tx/0xa9f4ce5675aa9fbfe0414d4ac9d3179bbedbc3743b84bc340ed74f119bf0bf41"
        },
        {
          "step": "fund",
          "transactionHash": "0x0ec726564774fa55c257d36df9d6d5967e51ab0cc6d31d241a2763aef533086d",
          "blockNumber": 124825800,
          "gasUsed": 97729,
          "effectiveGasPrice": 1000000000,
          "sponsored": false,
          "status": 1,
          "explorer": "https://testnet.bscscan.com/tx/0x0ec726564774fa55c257d36df9d6d5967e51ab0cc6d31d241a2763aef533086d"
        },
        {
          "step": "submit",
          "transactionHash": "0x40598fe724683dcb0ffd0e7e281198ad3e3079d30b7f83a3d19282d336022303",
          "blockNumber": 124825824,
          "gasUsed": 197134,
          "effectiveGasPrice": 1000000000,
          "sponsored": false,
          "status": 1,
          "explorer": "https://testnet.bscscan.com/tx/0x40598fe724683dcb0ffd0e7e281198ad3e3079d30b7f83a3d19282d336022303"
        },
        {
          "step": "settle",
          "transactionHash": "0x7d59cd272a1c38e8e60e53e79dcf5adc52166d151ec6c3c99286e3deabeb33c6",
          "blockNumber": 124827867,
          "gasUsed": 117631,
          "effectiveGasPrice": 1000000000,
          "sponsored": false,
          "status": 1,
          "explorer": "https://testnet.bscscan.com/tx/0x7d59cd272a1c38e8e60e53e79dcf5adc52166d151ec6c3c99286e3deabeb33c6"
        }
      ],
      "blockRange": {
        "firstBlock": 124825764,
        "lastBlock": 124827867
      }
    },
    "signedProtocolAction": {
      "category": "venus",
      "lab": "venus-health",
      "kind": "signed live corrective repay",
      "environment": "bsc-testnet",
      "signedAction": true,
      "broadcast": true,
      "keyMaterial": "none",
      "startedUtc": "2026-08-13T11:03:51.691Z",
      "chainId": 97,
      "startBlock": "124828129",
      "endBlock": "124828138",
      "deployer": "0xe8fb1F3329F1c9DD4d88aa666701f018CA5956ea",
      "comptroller": "0x94d1820b2D1c7c7452A163983Dc888CEC546b77D",
      "oracle": "0x3cD69251D04A28d887Ac14cbe2E14c52F3D57823",
      "vToken": "0xb7526572FFE56AB9D7489838Bf2E18e3323b441A",
      "underlying": "0xA11c8D9DC9b66E209Ef60F0C8D969D3CD988782c",
      "primaryTxHash": "0x4d34753485c5bfec78ea48e03c271b2e801d94c50f67d35982f08ba75158ed07",
      "actionTxs": [
        {
          "step": "repayBorrow",
          "hash": "0x4d34753485c5bfec78ea48e03c271b2e801d94c50f67d35982f08ba75158ed07",
          "blockNumber": "124828139",
          "status": 1,
          "gasUsed": "201170",
          "effectiveGasPrice": "100000000",
          "gasCostWei": "20117000000000"
        }
      ],
      "amounts": {
        "repayBaseUnits": "500000",
        "repayHuman": "0.5",
        "borrowBeforeBaseUnits": "1000000",
        "borrowAfterBaseUnits": "500000"
      },
      "healthFactor": {
        "before": {
          "healthFactor": 7.49999925,
          "healthFactorLabel": "7.499999",
          "weightedCollateralUsd": "3.749999625",
          "borrowUsd": "0.5",
          "accountLiquidityUsd": "3.499999999907899081",
          "shortfallUsd": "0",
          "borrowBaseUnits": "1000000"
        },
        "after": {
          "healthFactor": 14.9999985,
          "healthFactorLabel": "14.999999",
          "weightedCollateralUsd": "3.749999625",
          "borrowUsd": "0.25",
          "accountLiquidityUsd": "3.749999999907899081",
          "shortfallUsd": "0",
          "borrowBaseUnits": "500000"
        },
        "floor": 1.5,
        "keptAboveFloor": true
      },
      "safety": {
        "s1SimulatedBeforeBroadcast": true,
        "s1SimulationFlags": {
          "repayBorrow": true
        },
        "s2HealthFactorFloor": 1.5,
        "spendCeilingWei": "20000000000000000",
        "cumulativeGasWei": "20117000000000"
      },
      "gasWei": "20117000000000",
      "totalTbnbSpentWei": "20117000000000",
      "verification": {
        "debtReduced": true,
        "hfAboveFloor": true
      },
      "manifestHash": "sha256:96d8fd788958d72fd24a596d700ed6eba6b0f866f39232efeae787d02d5099fa"
    },
    "activityLedger": {
      "stages": [
        "TASK_SUBMITTED",
        "RANKED",
        "NEGOTIATED",
        "FUNDED",
        "RESULT_RECEIVED",
        "VALIDATED",
        "ACTION_SIGNED",
        "SETTLED",
        "RECORDED"
      ],
      "entries": [
        {
          "seq": 1,
          "atUtc": "2026-08-13T10:45:29.904Z",
          "stage": "TASK_SUBMITTED",
          "taskHash": "sha256:700ed2bcf6423a57e80a73ffec2b851b478f51b72240112811c1ef0b5cd0ac2b",
          "detail": "canonical venus task on bsc-testnet"
        },
        {
          "seq": 2,
          "atUtc": "2026-08-13T10:45:29.904Z",
          "stage": "RANKED",
          "taskHash": "sha256:700ed2bcf6423a57e80a73ffec2b851b478f51b72240112811c1ef0b5cd0ac2b",
          "agentKey": "97-9001",
          "detail": "chosen 97-9001 (first-party fallback) score 0.68 rankedAtBlock 124825683"
        },
        {
          "seq": 3,
          "atUtc": "2026-08-13T10:46:07Z",
          "stage": "NEGOTIATED",
          "taskHash": "sha256:700ed2bcf6423a57e80a73ffec2b851b478f51b72240112811c1ef0b5cd0ac2b",
          "agentKey": "97-9001",
          "detail": "ERC-8183 signed quote 0x3fa8ef1fbdd03117ae26301195874b7279288d32e8db48ecd78823abbdc83844 price 1000000000000000000 raw"
        },
        {
          "seq": 4,
          "atUtc": "2026-08-13T10:46:07Z",
          "stage": "FUNDED",
          "taskHash": "sha256:700ed2bcf6423a57e80a73ffec2b851b478f51b72240112811c1ef0b5cd0ac2b",
          "jobId": "505",
          "agentKey": "97-9001",
          "txHash": "0x0ec726564774fa55c257d36df9d6d5967e51ab0cc6d31d241a2763aef533086d",
          "detail": "ERC-8183 escrow funded 1 U for job 505"
        },
        {
          "seq": 5,
          "atUtc": "2026-08-13T10:46:07Z",
          "stage": "RESULT_RECEIVED",
          "taskHash": "sha256:700ed2bcf6423a57e80a73ffec2b851b478f51b72240112811c1ef0b5cd0ac2b",
          "jobId": "505",
          "agentKey": "97-9001",
          "txHash": "0x40598fe724683dcb0ffd0e7e281198ad3e3079d30b7f83a3d19282d336022303",
          "detail": "real venus proposal delivered; onchain deliverable 0x8720b058c395120077d2806f28edc7d09218752fd7163b229d4edaaafd923631"
        },
        {
          "seq": 6,
          "atUtc": "2026-08-13T11:03:32.454883Z",
          "stage": "VALIDATED",
          "taskHash": "sha256:700ed2bcf6423a57e80a73ffec2b851b478f51b72240112811c1ef0b5cd0ac2b",
          "jobId": "505",
          "agentKey": "97-9001",
          "detail": "action repayBorrow simulatable=true; proposalManifestHash sha256:63fd2a503cc4006aa091952b8d5c03c5d409a18c6ca250994633fb7eab192391"
        },
        {
          "seq": 7,
          "atUtc": "2026-08-13T11:03:51.691Z",
          "stage": "ACTION_SIGNED",
          "taskHash": "sha256:700ed2bcf6423a57e80a73ffec2b851b478f51b72240112811c1ef0b5cd0ac2b",
          "jobId": "505",
          "agentKey": "97-9001",
          "txHash": "0x4d34753485c5bfec78ea48e03c271b2e801d94c50f67d35982f08ba75158ed07",
          "detail": "user signed repayBorrow 500000 base units; HF 7.499999 -> 14.999999"
        },
        {
          "seq": 8,
          "atUtc": "2026-08-13T11:03:32.454883Z",
          "stage": "SETTLED",
          "taskHash": "sha256:700ed2bcf6423a57e80a73ffec2b851b478f51b72240112811c1ef0b5cd0ac2b",
          "jobId": "505",
          "agentKey": "97-9001",
          "txHash": "0x7d59cd272a1c38e8e60e53e79dcf5adc52166d151ec6c3c99286e3deabeb33c6",
          "detail": "job settled COMPLETED; provider payout 1000000000000000000 raw"
        },
        {
          "seq": 9,
          "atUtc": "2026-08-13T11:04:16.633Z",
          "stage": "RECORDED",
          "taskHash": "sha256:700ed2bcf6423a57e80a73ffec2b851b478f51b72240112811c1ef0b5cd0ac2b",
          "jobId": "505",
          "agentKey": "97-9001",
          "detail": "full venus lifecycle recorded"
        }
      ],
      "activityHash": "sha256:87cb392f1c7d6f3c64aaf2a1688f56ae10459c89c32109509c927dc105b41272"
    },
    "independentReVerification": {
      "jobStatus": "COMPLETED",
      "jobCompleted": true,
      "onchainDeliverable": "0x8720b058c395120077d2806f28edc7d09218752fd7163b229d4edaaafd923631",
      "actionTxs": [
        {
          "hash": "0x4d34753485c5bfec78ea48e03c271b2e801d94c50f67d35982f08ba75158ed07",
          "block": 124828139,
          "status": 1,
          "status_ok": true
        }
      ],
      "allActionsOk": true,
      "checkedBlock": 124828183
    },
    "gas": {
      "jobNativeWei": "1269801000000000",
      "actionNativeWei": "20117000000000",
      "totalNativeWei": "1289918000000000",
      "totalTbnb": 0.001289918,
      "ceilingTbnb": 0.05
    },
    "reproduceCommands": [
      "cd labs/reference-agent && PORT=8003 REFERENCE_AGENT_HOST=127.0.0.1 PYTHONPATH=$PWD .venv/bin/python -m atelo_reference_agent",
      "cloudflared tunnel --url http://127.0.0.1:8003 ; set REFERENCE_AGENT_PUBLIC_URL in .env",
      "pnpm tsx labs/agent-probe/src/probe-cli.ts $REFERENCE_AGENT_PUBLIC_URL",
      "REFERENCE_AGENT_ID=1809 REFERENCE_AGENT_ALLOW_REGISTER=yes labs/reference-agent/.venv/bin/python labs/reference-agent/scripts/register.py --force --self-pay",
      "pnpm tsx labs/atelo-core/src/live-venus-plan.ts",
      "REFERENCE_AGENT_ID=1809 labs/reference-agent/.venv/bin/python labs/reference-agent/scripts/live_category_job.py --category venus --plan <plan.json> --out <job.json>",
      "node --env-file=.env --import tsx <category action script>",
      "labs/reference-agent/.venv/bin/python labs/reference-agent/scripts/reverify_action.py --job-id <id> --action-tx <hash> --out <reverify.json>",
      "pnpm tsx labs/atelo-core/src/assemble-lifecycle.ts"
    ],
    "manifestHash": "sha256:fb47f0fd16a5682cc70bffbfb1b6978af936a3d4df104bcc1c211a0784fa21a2"
  }
};

export const lifecycles: Record<Category, RawLifecycle> = data;
