// GENERATED by packages/core/scripts/gen-data.mjs — do not edit by hand.
import type { RawLineage, RawGreenfield } from "../raw";

const records = {
  "501": {
    "agentId": "97:registry:1809",
    "category": "grid",
    "dataCutoffBlock": 124815212,
    "endBlock": 124815147,
    "evidenceContentHash": "sha256:23f8e909a1b6452c494cbe4136bc3f7c4a721547e012f1e5023ed0b73354a468",
    "evidenceUri": "gnfd://atelo-lineage-9e2c/23f8e909a1b6452c494cbe4136bc3f7c4a721547e012f1e5023ed0b73354a468.json",
    "jobId": "501",
    "mandateHash": "0x2cdf16907bcff0f6ab8428c14ae6e911decbb62d4b25b3df77cc830439449e3c",
    "metricDetail": {
      "formula": "(quotedAmountOut - executedAmountOut) * 10000 / quotedAmountOut",
      "inputs": {
        "amountIn": "2000000000000000",
        "direction": "SELL_WBNB",
        "executedAmountOut": "13682220",
        "quotedAmountOut": "13682220"
      },
      "metric": "realized_slippage_bps",
      "scoreVersion": "grid-v1",
      "unit": "bps",
      "value": 0
    },
    "metrics": {
      "realized_slippage_bps": 0
    },
    "previousRecordHash": null,
    "recordHash": "sha256:059f5c59ee36054bad9b24bc470565fb83b294cdfe7eb09cbfbf7eeae34f50a9",
    "schemaVersion": "atelo-lineage/1",
    "scoreVersion": "grid-v1",
    "selfClaims": {},
    "startBlock": 124812451,
    "status": "VERIFIED",
    "taskHash": "sha256:b9a798b5f636a01f2a24beed6bbe70711bef073840026e4c2fcdd3a55854ed6c",
    "transactions": [
      "0xe6a7a449a6a1c65c6e77d067151afdecadaa21228130f8d2ca93997d248220f2",
      "0x2b93c8f104c80b95b4c87341702ac5701d6f4d0010aef5753702a9ee9f5d0904",
      "0xed74728f903303be19b54ce767b534e170bdc18db4991c94ce71cef0f41c270e",
      "0x27c9e482da54e60870aab0178e2cbf2e0eb33afebf4fc54494453528863a9967",
      "0x516f13ba3e3cdbc091e1814046f5338f5a31935e7a50c13d0bfab36457e26c67",
      "0x4f8e475d9f89c20b713fd09db82fa43c832aca03e512d158b56da3c68e64c3ca",
      "0xdeedaec2a4416dba70189cc8872fb46663b668ef7ef5602462edc644f309fed5",
      "0x6368a27aac739f92b4804c5f11d3224f978de740a9bb521e21b5e84b362a2afb"
    ]
  },
  "503": {
    "agentId": "97:registry:1809",
    "category": "rebalancing",
    "dataCutoffBlock": 124822636,
    "endBlock": 124822584,
    "evidenceContentHash": "sha256:cc1e7ca3efc1d8ad29d12414ae620b4ef67e42c686bfd2de34a103d51effa2ab",
    "evidenceUri": "gnfd://atelo-lineage-9e2c/cc1e7ca3efc1d8ad29d12414ae620b4ef67e42c686bfd2de34a103d51effa2ab.json",
    "jobId": "503",
    "mandateHash": "0xd775388bd25846038aaabbeb42aa9ce617dd3af9ab308bc1b0df5dbdcdef1285",
    "metricDetail": {
      "formula": "proposedTickLower <= poolTick < proposedTickUpper",
      "inputs": {
        "poolTick": 188036,
        "proposedTickLower": 187986,
        "proposedTickUpper": 188086
      },
      "metric": "position_in_range",
      "scoreVersion": "rebalancing-v1",
      "unit": "boolean",
      "value": true
    },
    "metrics": {
      "position_in_range": true
    },
    "previousRecordHash": "sha256:059f5c59ee36054bad9b24bc470565fb83b294cdfe7eb09cbfbf7eeae34f50a9",
    "recordHash": "sha256:89585a929b93866bb9d93e835759a2b98fc9384330377f3f6409bae258c02d72",
    "schemaVersion": "atelo-lineage/1",
    "scoreVersion": "rebalancing-v1",
    "selfClaims": {},
    "startBlock": 124818707,
    "status": "VERIFIED",
    "taskHash": "sha256:59578b6bebad8ef6dd4674f81621d792511317442e0650c8659fdbfd7f28c362",
    "transactions": [
      "0x4f99fadae04cd2396ab8f9581316acfa42a7414005587192ee7518731b123d3e",
      "0x55a9d3867d685f25915ff028954aa38fba02c9a318d8f5946e714edcd0b34264",
      "0x7ed68722d43c324ca2ea96d1cdc7977857e617dadb359359cbd5ad9b810f67dd",
      "0xdcb85d2473da3f9d10b294944b3b87b816f26b75b9473fdf8766fe6cf7765814",
      "0x30a38cc53653c2e4f68cbc7bafe25b34fbe44c8d387b3bd28dda7d937187b82a",
      "0x44e76659b6237881bf6bf76d7ebb8b53a5032d8781611606b139ab0cc37fd0fe",
      "0x3abcfbf4b797aec02849ddd35fa810ae111969ba276d2c965f7523ebaf150101",
      "0xd3ab91a953e927c890803b5fcd795816f56f1f5c654648ddfcbd7c29f68b9b78",
      "0x421f0a84dd46610714bfa24db6d9faf7d1f3fc13e449a023393fe600ed8eba4e"
    ]
  },
  "504": {
    "agentId": "97:registry:1809",
    "category": "yield",
    "dataCutoffBlock": 124825598,
    "endBlock": 124825547,
    "evidenceContentHash": "sha256:01fadd1925651f97bbdc1ef12da25d47011efbc8e7d8c55428f3802a7101f846",
    "evidenceUri": "gnfd://atelo-lineage-9e2c/01fadd1925651f97bbdc1ef12da25d47011efbc8e7d8c55428f3802a7101f846.json",
    "jobId": "504",
    "mandateHash": "0xbdfac255615164c4af02342374abef9812e2f30f1ed81f27ebeee9e421b64a6c",
    "metricDetail": {
      "formula": "realized APR unmeasurable via testnet view calls; labeled UNKNOWN_TESTNET, never a fabricated zero",
      "inputs": {
        "advertisedVsRealized": "realized APR is unmeasurable via view calls on testnet; deposit is opened to hold a live concentrated position",
        "feeTier": 100,
        "realizedApr": "UNKNOWN_TESTNET",
        "tickLower": 187986,
        "tickUpper": 188086,
        "tvlUsdt": 4026.9430920896916
      },
      "metric": "realized_apr_pct",
      "scoreVersion": "yield-v1",
      "unit": "apr_pct",
      "value": "UNKNOWN_TESTNET"
    },
    "metrics": {
      "realized_apr_pct": "UNKNOWN_TESTNET"
    },
    "previousRecordHash": "sha256:89585a929b93866bb9d93e835759a2b98fc9384330377f3f6409bae258c02d72",
    "recordHash": "sha256:5e52c4c571dbc15531e32e4cfeadb23e87727b80ad565311068f051139a28db9",
    "schemaVersion": "atelo-lineage/1",
    "scoreVersion": "yield-v1",
    "selfClaims": {
      "advertisedVsRealized": "realized APR is unmeasurable via view calls on testnet; deposit is opened to hold a live concentrated position",
      "choice": "WBNB/USDT 100"
    },
    "startBlock": 124822787,
    "status": "UNVERIFIED",
    "taskHash": "sha256:49ca4b9d8577853e8523288df526f0a03b1f61fb5915c8f7415abda981303dc0",
    "transactions": [
      "0x730c567cfba19d0de5c8ed8a9ee96c89988171a6b76be29973fa4b3d4a774add",
      "0x44894c5c73ba8c4116adeaa319f4bfbcdd0bfbe4c72629753c775d5f5bb31bb6",
      "0xafcba770fc1debe546fa2cef18505a4931b4e8a57469906acfbb596d9232a25c",
      "0xaf4f0b586006530bd2e4934d17cf24ea961027cb1c3afd1c39aa96c669c9b46b",
      "0xab31fa83772bad3228079ba48446bb9604758efaadd14ca8a6a4c9f129f739e7",
      "0x12cafe9ed038a207ffb609526cddf7fed7795c50c6a743f6cbf5c6981f177bd9",
      "0x0a53c350f78aa019a3637d2476e3fcdf33a23a09dc356110f6e060e681dc1570"
    ]
  },
  "505": {
    "agentId": "97:registry:1809",
    "category": "venus",
    "dataCutoffBlock": 124828183,
    "endBlock": 124828139,
    "evidenceContentHash": "sha256:9252c772ee6b4cae96fba583e33d78b17a3c6baa9361b61c1ec335a91612d3c0",
    "evidenceUri": "gnfd://atelo-lineage-9e2c/9252c772ee6b4cae96fba583e33d78b17a3c6baa9361b61c1ec335a91612d3c0.json",
    "jobId": "505",
    "mandateHash": "0x3fa8ef1fbdd03117ae26301195874b7279288d32e8db48ecd78823abbdc83844",
    "metricDetail": {
      "formula": "healthFactorAfter - healthFactorBefore",
      "inputs": {
        "floor": 1.5,
        "healthFactorAfter": 14.9999985,
        "healthFactorBefore": 7.49999925
      },
      "metric": "health_factor_change",
      "scoreVersion": "venus-v1",
      "unit": "hf",
      "value": 7.49999925
    },
    "metrics": {
      "health_factor_change": 7.49999925
    },
    "previousRecordHash": "sha256:5e52c4c571dbc15531e32e4cfeadb23e87727b80ad565311068f051139a28db9",
    "recordHash": "sha256:2eb03fc928bf440abd2f3dbd9dd8a48607212ca2a31c47ff790def16c024cdde",
    "schemaVersion": "atelo-lineage/1",
    "scoreVersion": "venus-v1",
    "selfClaims": {},
    "startBlock": 124825764,
    "status": "VERIFIED",
    "taskHash": "sha256:700ed2bcf6423a57e80a73ffec2b851b478f51b72240112811c1ef0b5cd0ac2b",
    "transactions": [
      "0x5b904752737146125b978eb4e122fef316f52bbec9dbe3055e481683ab50fcf4",
      "0x1cc3de4bae32c1e865922e731247db937c3b10bb4d7f891d8656069e54508f93",
      "0xa9f4ce5675aa9fbfe0414d4ac9d3179bbedbc3743b84bc340ed74f119bf0bf41",
      "0x0ec726564774fa55c257d36df9d6d5967e51ab0cc6d31d241a2763aef533086d",
      "0x40598fe724683dcb0ffd0e7e281198ad3e3079d30b7f83a3d19282d336022303",
      "0x7d59cd272a1c38e8e60e53e79dcf5adc52166d151ec6c3c99286e3deabeb33c6",
      "0x4d34753485c5bfec78ea48e03c271b2e801d94c50f67d35982f08ba75158ed07"
    ]
  }
};

export const lineageRecords: Record<string, RawLineage> = records;

const greenfieldData = {
  "artifact": "atelo-phase-04-greenfield-upload",
  "balances": {
    "afterTBNB": 0.47914047201259274,
    "afterWei": "479140472012592738",
    "beforeTBNB": 0.47915847201259276,
    "beforeWei": "479158472012592738",
    "denom": "BNB"
  },
  "bucket": "atelo-lineage-9e2c",
  "chain": "greenfield_5600-1",
  "createBucketTx": "0C3FD0F191F79BCC81B53AB415044053C9D1509E4C63AC6CECD66D8BFD2B7049",
  "environment": "greenfield-testnet",
  "generatedAt": "2026-08-13T12:52:53.539Z",
  "identityWallet": "0x6945EE254481302AD292Dfc8F7f27c4B065Af96d",
  "keyMaterial": "none",
  "objects": [
    {
      "alreadyExisted": false,
      "category": "yield",
      "contentAddressIdentityOk": true,
      "createObjectTx": "EC28A8C3D774729122C4296CEDF711D4744120C16A3192EE9ACBAD74BDA6F24D",
      "downloadVerified": true,
      "downloadedByteSha256": "sha256:13804c62a4e0ef57fc6fb0eb8b08a561cbafd847ab5b863aaea5745b091110c7",
      "gnfdUri": "gnfd://atelo-lineage-9e2c/01fadd1925651f97bbdc1ef12da25d47011efbc8e7d8c55428f3802a7101f846.json",
      "greenfieldChecksums": [
        "vwK3Gbs+Oko6y8B4/sAsNgnReB+LYjbADlW4Dps4tNI=",
        "OG8O0BJ0q5ZfZ+cmihhcS6zsyKBdQfyrcwsHIIaPpY0=",
        "1hBRiMHS2Qmb19bVSaAoV4LfxL9mpRoDTf/RRbqwGUE=",
        "M0qLvdt1Occcgqnt7JHU7e5uVtahPP0lGnnsRd28Efw=",
        "QbaTJsDxBw8LrpiYjh4gtuSvrI6s3f9D6TQ25PGSqqU=",
        "L0BUO1Gs4NUYBwJWV7tXdjJemSMzBX2EgDL1lCABxkA=",
        "wm5nSDdOuKkZ+eqE7mqISd/yKvNSWsmvhHoQDSI261c="
      ],
      "objectName": "01fadd1925651f97bbdc1ef12da25d47011efbc8e7d8c55428f3802a7101f846.json",
      "ourSha256": "sha256:01fadd1925651f97bbdc1ef12da25d47011efbc8e7d8c55428f3802a7101f846",
      "payloadSize": 5330,
      "spDownloadUrl": "https://gnfd-testnet-sp3.bnbchain.org/view/atelo-lineage-9e2c/01fadd1925651f97bbdc1ef12da25d47011efbc8e7d8c55428f3802a7101f846.json"
    },
    {
      "alreadyExisted": true,
      "category": "grid",
      "contentAddressIdentityOk": true,
      "createObjectTx": "173F5F0E2D2161EDF14BCA8BD585A405E0E66C5774945DED1B4E172C7B7338D6",
      "downloadVerified": true,
      "downloadedByteSha256": "sha256:f4d181b9168ec1e2791c74911a2ff3d26934318ca025b212496fa57ba9785794",
      "gnfdUri": "gnfd://atelo-lineage-9e2c/23f8e909a1b6452c494cbe4136bc3f7c4a721547e012f1e5023ed0b73354a468.json",
      "greenfieldChecksums": [
        "+yC1Tuf1Lcc1rqPiDKlwDtDV6qIs8gU+eaBhE5wLmOQ=",
        "I92YBaHldQJ5OvWquyrr7u7yjH9x3DMeASxuCXQVrKc=",
        "UYnX6JIcHUhBuPDvDWWadiXc7LwcOPFpYm72cT8nNkM=",
        "9v7Iv0Dn9I0/WBKEenWF74UX59UdmWpgWVdhjKZ/k3M=",
        "JbR0Nh3DBu/FaZj1TTniYRiIJkt33SxdUU5BFIZH7E4=",
        "h3yHhUGFodmOJBYzq7mQNXRJX74y6JihU7NZR45hEFA=",
        "UGMthTJRO8sJoAWatppJHBjX9w9qP7aS4fsXgUW0jtY="
      ],
      "objectName": "23f8e909a1b6452c494cbe4136bc3f7c4a721547e012f1e5023ed0b73354a468.json",
      "ourSha256": "sha256:23f8e909a1b6452c494cbe4136bc3f7c4a721547e012f1e5023ed0b73354a468",
      "payloadSize": 5717,
      "spDownloadUrl": "https://gnfd-testnet-sp3.bnbchain.org/view/atelo-lineage-9e2c/23f8e909a1b6452c494cbe4136bc3f7c4a721547e012f1e5023ed0b73354a468.json"
    },
    {
      "alreadyExisted": false,
      "category": "venus",
      "contentAddressIdentityOk": true,
      "createObjectTx": "7AB6458C689D27943AF442FCEC9A600F1A298D03ACC3054A2F5B66D37457C643",
      "downloadVerified": true,
      "downloadedByteSha256": "sha256:312235fcc1ccb5659f6bf0ac27774e070b678629e31d0b45aa4ad016e0077a85",
      "gnfdUri": "gnfd://atelo-lineage-9e2c/9252c772ee6b4cae96fba583e33d78b17a3c6baa9361b61c1ec335a91612d3c0.json",
      "greenfieldChecksums": [
        "CVm7u0EyMSu2c9wo5MOWowoMOH7jCw15INiLPmaEo2A=",
        "2zvj+BK6qxE6XhyEPfSuQ08oscMwNgPr9cWa+u5+Rj4=",
        "pmjqFnwahilMn1hVIJnVBEcrLzAjEiWklgQbR6k1AiM=",
        "ZaPq33Wu9/lRfnmxTJBYdBaxCRTIji9pUZqtpKh/Mog=",
        "OtwYRr8fVrlJDNcMqQih8/NHasjEMiLCQ9UfKN0A5XI=",
        "I4j598xfzVYFfkw1PYdBC8c5JLtYeXVi5H0mMe2QTzc=",
        "oB16HW3PqcxkU7+pIQwszQFVr75OD4h15Vld23ihxzM="
      ],
      "objectName": "9252c772ee6b4cae96fba583e33d78b17a3c6baa9361b61c1ec335a91612d3c0.json",
      "ourSha256": "sha256:9252c772ee6b4cae96fba583e33d78b17a3c6baa9361b61c1ec335a91612d3c0",
      "payloadSize": 5142,
      "spDownloadUrl": "https://gnfd-testnet-sp3.bnbchain.org/view/atelo-lineage-9e2c/9252c772ee6b4cae96fba583e33d78b17a3c6baa9361b61c1ec335a91612d3c0.json"
    },
    {
      "alreadyExisted": false,
      "category": "rebalancing",
      "contentAddressIdentityOk": true,
      "createObjectTx": "94C5CB7C3AED0DF71E87ABCC8AF64FFA657FB8CA6ED3FF0D22764A45BBBFD9D7",
      "downloadVerified": true,
      "downloadedByteSha256": "sha256:84cdddad12b65917720d1945a52f42dd0f6a458e679a3e6c78aa5fc6c201fa55",
      "gnfdUri": "gnfd://atelo-lineage-9e2c/cc1e7ca3efc1d8ad29d12414ae620b4ef67e42c686bfd2de34a103d51effa2ab.json",
      "greenfieldChecksums": [
        "gnsvOH88kmRn9oO84OYqqhwfLIDJ9z8Wdp+MONC0hJQ=",
        "0rSsJ9aFLe3v3SCPb93lTvpj4ERynwJd86JQRuBbt3g=",
        "+Gw/7lnc4fb/sqjFIQyLA9UxofaH3efFQySZjqd9aD4=",
        "mkSIoWaZqMJJvJ0hYgHGqPLzl+Cvncx+qqXEhMNWIx8=",
        "PXaQWFaIvA/i50IYl9QhEJtPIPOpl8W+j6JfZssLTgM=",
        "qQQXQ2M4dO+m8tb6MkToOgMlOK78DdFtYP0OZIPW+1o=",
        "120CDreDVcMZGD/IUxwi6rWK6syym8iQvEKbgphpGlc="
      ],
      "objectName": "cc1e7ca3efc1d8ad29d12414ae620b4ef67e42c686bfd2de34a103d51effa2ab.json",
      "ourSha256": "sha256:cc1e7ca3efc1d8ad29d12414ae620b4ef67e42c686bfd2de34a103d51effa2ab",
      "payloadSize": 5296,
      "spDownloadUrl": "https://gnfd-testnet-sp3.bnbchain.org/view/atelo-lineage-9e2c/cc1e7ca3efc1d8ad29d12414ae620b4ef67e42c686bfd2de34a103d51effa2ab.json"
    }
  ],
  "reproduce": [
    "node --env-file=.env --import tsx labs/lineage/src/greenfield-upload.ts",
    "GREENFIELD_ENABLED=1 node --env-file=.env --import tsx labs/lineage/src/run.ts",
    "GREENFIELD_ENABLED=1 node --env-file=.env --import tsx labs/lineage/src/run-replay.ts artifacts/phase-04/lineage/501.json"
  ],
  "rpc": "https://gnfd-testnet-fullnode-tendermint-us.bnbchain.org",
  "sp": {
    "endpoint": "https://gnfd-testnet-sp3.bnbchain.org",
    "operatorAddress": "0x5ccF0F6b78a37Ef4e2CcBC10D155c28Fb8bE9BaF"
  }
};

export const greenfield: RawGreenfield = greenfieldData;
