// GENERATED by packages/core/scripts/gen-data.mjs — do not edit by hand.
import type { RawSummary, RawReport } from "../raw";

const summary = {
  "kind": "qualification-summary",
  "phase": "01",
  "generatedUtc": "2026-08-12T20:47:01.662Z",
  "gitCommit": "4d3b6d9629ac24c8be568cdc08d0216f9f18fe6a",
  "reproduce": "pnpm tsx labs/qualification/src/run.ts",
  "inputs": {
    "detailFiles": [
      "artifacts/phase-00/raw/agent-details-2026-08-11T21-50-47-380Z-raw.json",
      "artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
      "artifacts/phase-00/raw/agent-details-2026-08-11T23-58-09-394Z-raw.json"
    ],
    "probeFiles": [
      "artifacts/phase-00/endpoint-probe-2026-08-11T21-52-01-299Z.json",
      "artifacts/phase-00/endpoint-probe-2026-08-11T21-53-13-676Z.json",
      "artifacts/phase-00/endpoint-probe-2026-08-11T21-53-48-867Z.json",
      "artifacts/phase-00/endpoint-probe-2026-08-11T23-48-36-305Z.json",
      "artifacts/phase-00/endpoint-probe-2026-08-12T00-00-28-103Z.json",
      "artifacts/phase-00/endpoint-probe-2026-08-12T17-20-24-393Z.json",
      "artifacts/phase-00/endpoint-probe-2026-08-12T18-19-31-058Z.json"
    ],
    "settledLifecycleFile": "artifacts/phase-00/e5-lifecycle-settled-2026-08-12T18-43-11-624Z.json"
  },
  "funnel": {
    "totalDiscovered": 1772,
    "examinedRecords": 70,
    "byState": {
      "DISCOVERED": 0,
      "METADATA_VALID": 3,
      "REACHABLE": 0,
      "PROTOCOL_COMPATIBLE": 0,
      "TEST_JOB_PASSED": 1,
      "PERFORMANCE_INDEXED": 0,
      "HIREABLE": 0,
      "REJECTED": 66
    },
    "byHighestStage": {
      "DISCOVERED": 41,
      "METADATA_VALID": 9,
      "REACHABLE": 19,
      "PROTOCOL_COMPATIBLE": 0,
      "TEST_JOB_PASSED": 1,
      "PERFORMANCE_INDEXED": 0,
      "HIREABLE": 0
    },
    "byRejectionReason": {
      "DEAD_DOMAIN": 9,
      "NO_PROTOCOL_DETECTED": 19,
      "NO_ENDPOINT": 15,
      "PRIVATE_OR_LOCAL_ENDPOINT": 8,
      "TEMPLATE_ENDPOINT": 15
    },
    "thirdParty": {
      "examined": 69,
      "testJobPassed": 0,
      "hireable": 0
    },
    "firstParty": {
      "examined": 1,
      "testJobPassed": 1
    },
    "perCategory": {
      "rebalancing": {
        "examined": 13,
        "reachableOrBetter": 1,
        "testJobPassed": 1,
        "firstPartyOnly": false
      },
      "grid": {
        "examined": 16,
        "reachableOrBetter": 1,
        "testJobPassed": 1,
        "firstPartyOnly": false
      },
      "yield": {
        "examined": 9,
        "reachableOrBetter": 1,
        "testJobPassed": 1,
        "firstPartyOnly": false
      },
      "health": {
        "examined": 9,
        "reachableOrBetter": 1,
        "testJobPassed": 1,
        "firstPartyOnly": false
      },
      "none": {
        "examined": 36,
        "reachableOrBetter": 0,
        "testJobPassed": 0,
        "firstPartyOnly": false
      }
    }
  },
  "note": "Registry identity count is not a callable-agent count. First-party (Atelo reference agent) counts are kept strictly separate from third-party diversity. Self-declared protocols never advance an agent past METADATA_VALID."
};

export const qualificationSummary: RawSummary = summary;

const reports = [
  {
    "key": "97-1142",
    "chainId": 97,
    "tokenId": "1142",
    "name": "blockchain-news-agent",
    "owner": "0x5503b1da55196585112072ca88c6cce1eb9a955a",
    "thirdParty": true,
    "categories": [
      "none"
    ],
    "declaredProtocols": [
      "A2A"
    ],
    "declaredEndpoints": [
      "http://localhost:8081"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "DISCOVERED",
    "rejectionReasonCode": "PRIVATE_OR_LOCAL_ENDPOINT",
    "rejectionReason": "all declared endpoints are loopback or private-network targets",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-58-09-394Z-raw.json",
        "reasonCode": "PRIVATE_OR_LOCAL_ENDPOINT",
        "reason": "all declared endpoints are loopback or private-network targets"
      }
    ]
  },
  {
    "key": "97-1183",
    "chainId": 97,
    "tokenId": "1183",
    "name": "xsd-111-agent",
    "owner": "0x708ea5308e8a2227b6125b335298fb5e64263d99",
    "thirdParty": true,
    "categories": [
      "grid"
    ],
    "declaredProtocols": [],
    "declaredEndpoints": [],
    "finalState": "REJECTED",
    "highestStageReached": "DISCOVERED",
    "rejectionReasonCode": "NO_ENDPOINT",
    "rejectionReason": "no HTTP(S) endpoint declared in metadata",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "NO_ENDPOINT",
        "reason": "no HTTP(S) endpoint declared in metadata"
      }
    ]
  },
  {
    "key": "97-1236",
    "chainId": 97,
    "tokenId": "1236",
    "name": "portfolio-rebalancer",
    "owner": "0xc4815b153d76a9b67312c2075e369d79b3ff7299",
    "thirdParty": true,
    "categories": [
      "rebalancing"
    ],
    "declaredProtocols": [
      "A2A"
    ],
    "declaredEndpoints": [
      "https://portfolio-rebalancer.bnbagent.example/.well-known/agent-card.json"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "DISCOVERED",
    "rejectionReasonCode": "DEAD_DOMAIN",
    "rejectionReason": "declared endpoint uses a reserved .example domain that cannot resolve",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "DEAD_DOMAIN",
        "reason": "declared endpoint uses a reserved .example domain that cannot resolve"
      }
    ]
  },
  {
    "key": "97-1237",
    "chainId": 97,
    "tokenId": "1237",
    "name": "portfolio-rebalancer",
    "owner": "0xc4815b153d76a9b67312c2075e369d79b3ff7299",
    "thirdParty": true,
    "categories": [
      "rebalancing"
    ],
    "declaredProtocols": [
      "A2A"
    ],
    "declaredEndpoints": [
      "https://portfolio-rebalancer.bnbagent.example/.well-known/agent-card.json"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "DISCOVERED",
    "rejectionReasonCode": "DEAD_DOMAIN",
    "rejectionReason": "declared endpoint uses a reserved .example domain that cannot resolve",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "DEAD_DOMAIN",
        "reason": "declared endpoint uses a reserved .example domain that cannot resolve"
      }
    ]
  },
  {
    "key": "97-1273",
    "chainId": 97,
    "tokenId": "1273",
    "name": "GENESIS",
    "owner": "0x047d491771f358d0ff48e6a8388565c3f1011a11",
    "thirdParty": true,
    "categories": [
      "grid"
    ],
    "declaredProtocols": [],
    "declaredEndpoints": [],
    "finalState": "REJECTED",
    "highestStageReached": "DISCOVERED",
    "rejectionReasonCode": "NO_ENDPOINT",
    "rejectionReason": "no HTTP(S) endpoint declared in metadata",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "NO_ENDPOINT",
        "reason": "no HTTP(S) endpoint declared in metadata"
      }
    ]
  },
  {
    "key": "97-1274",
    "chainId": 97,
    "tokenId": "1274",
    "name": "GENESIS",
    "owner": "0x047d491771f358d0ff48e6a8388565c3f1011a11",
    "thirdParty": true,
    "categories": [
      "grid"
    ],
    "declaredProtocols": [],
    "declaredEndpoints": [],
    "finalState": "REJECTED",
    "highestStageReached": "DISCOVERED",
    "rejectionReasonCode": "NO_ENDPOINT",
    "rejectionReason": "no HTTP(S) endpoint declared in metadata",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "NO_ENDPOINT",
        "reason": "no HTTP(S) endpoint declared in metadata"
      }
    ]
  },
  {
    "key": "97-1275",
    "chainId": 97,
    "tokenId": "1275",
    "name": "GENESIS",
    "owner": "0x047d491771f358d0ff48e6a8388565c3f1011a11",
    "thirdParty": true,
    "categories": [
      "grid"
    ],
    "declaredProtocols": [],
    "declaredEndpoints": [],
    "finalState": "REJECTED",
    "highestStageReached": "DISCOVERED",
    "rejectionReasonCode": "NO_ENDPOINT",
    "rejectionReason": "no HTTP(S) endpoint declared in metadata",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "NO_ENDPOINT",
        "reason": "no HTTP(S) endpoint declared in metadata"
      }
    ]
  },
  {
    "key": "97-1279",
    "chainId": 97,
    "tokenId": "1279",
    "name": "BNBHack LP Agent",
    "owner": "0xd49917f80802898495510e4f476dbfc91aedf247",
    "thirdParty": true,
    "categories": [
      "rebalancing"
    ],
    "declaredProtocols": [],
    "declaredEndpoints": [],
    "finalState": "REJECTED",
    "highestStageReached": "DISCOVERED",
    "rejectionReasonCode": "NO_ENDPOINT",
    "rejectionReason": "no HTTP(S) endpoint declared in metadata",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "NO_ENDPOINT",
        "reason": "no HTTP(S) endpoint declared in metadata"
      }
    ]
  },
  {
    "key": "97-129",
    "chainId": 97,
    "tokenId": "129",
    "name": "YieldOracle",
    "owner": "0x669745979a8b584304d535d13727915d2cf532e4",
    "thirdParty": true,
    "categories": [
      "yield"
    ],
    "declaredProtocols": [
      "A2A"
    ],
    "declaredEndpoints": [
      "https://yieldoracle.agentx.network/.well-known/agent-card.json"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "METADATA_VALID",
    "rejectionReasonCode": "DEAD_DOMAIN",
    "rejectionReason": "endpoint probed under the safety policy and did not respond as a live service",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "METADATA_VALID",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-58-09-394Z-raw.json"
      },
      {
        "from": "METADATA_VALID",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-58-09-394Z-raw.json",
        "reasonCode": "DEAD_DOMAIN",
        "reason": "endpoint probed under the safety policy and did not respond as a live service"
      }
    ]
  },
  {
    "key": "97-1313",
    "chainId": 97,
    "tokenId": "1313",
    "name": "RegimeAdaptiveMomentumAgent",
    "owner": "0xeb7bf36aab4912c955474206ef0b835170389655",
    "thirdParty": true,
    "categories": [
      "grid"
    ],
    "declaredProtocols": [],
    "declaredEndpoints": [],
    "finalState": "REJECTED",
    "highestStageReached": "DISCOVERED",
    "rejectionReasonCode": "NO_ENDPOINT",
    "rejectionReason": "no HTTP(S) endpoint declared in metadata",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "NO_ENDPOINT",
        "reason": "no HTTP(S) endpoint declared in metadata"
      }
    ]
  },
  {
    "key": "97-1335",
    "chainId": 97,
    "tokenId": "1335",
    "name": "Triton",
    "owner": "0xebbf0b6cfbd3cc647ff60f2d960a707aab15d9af",
    "thirdParty": true,
    "categories": [
      "grid"
    ],
    "declaredProtocols": [],
    "declaredEndpoints": [],
    "finalState": "REJECTED",
    "highestStageReached": "DISCOVERED",
    "rejectionReasonCode": "NO_ENDPOINT",
    "rejectionReason": "no HTTP(S) endpoint declared in metadata",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "NO_ENDPOINT",
        "reason": "no HTTP(S) endpoint declared in metadata"
      }
    ]
  },
  {
    "key": "97-1347",
    "chainId": 97,
    "tokenId": "1347",
    "name": "Boomerang AI",
    "owner": "0x0db2134c3807fa42950eb1fc39fb0d77e0a0b09c",
    "thirdParty": true,
    "categories": [
      "grid"
    ],
    "declaredProtocols": [],
    "declaredEndpoints": [
      "https://boomerang.deegalabs.ai/erc8183/status"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "METADATA_VALID",
    "rejectionReasonCode": "DEAD_DOMAIN",
    "rejectionReason": "endpoint probed under the safety policy and did not respond as a live service",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "METADATA_VALID",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json"
      },
      {
        "from": "METADATA_VALID",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "DEAD_DOMAIN",
        "reason": "endpoint probed under the safety policy and did not respond as a live service"
      }
    ]
  },
  {
    "key": "97-135",
    "chainId": 97,
    "tokenId": "135",
    "name": "LiquidityScout",
    "owner": "0x669745979a8b584304d535d13727915d2cf532e4",
    "thirdParty": true,
    "categories": [
      "grid"
    ],
    "declaredProtocols": [
      "A2A"
    ],
    "declaredEndpoints": [
      "https://liquidityscout.agentx.network/.well-known/agent-card.json"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "METADATA_VALID",
    "rejectionReasonCode": "DEAD_DOMAIN",
    "rejectionReason": "endpoint probed under the safety policy and did not respond as a live service",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "METADATA_VALID",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-58-09-394Z-raw.json"
      },
      {
        "from": "METADATA_VALID",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-58-09-394Z-raw.json",
        "reasonCode": "DEAD_DOMAIN",
        "reason": "endpoint probed under the safety policy and did not respond as a live service"
      }
    ]
  },
  {
    "key": "97-1360",
    "chainId": 97,
    "tokenId": "1360",
    "name": "rangepilot-strategy-agent",
    "owner": "0x6d662707910440fbe94f13bfc103e61018b77808",
    "thirdParty": true,
    "categories": [
      "rebalancing",
      "grid"
    ],
    "declaredProtocols": [
      "A2A"
    ],
    "declaredEndpoints": [
      "https://localhost:8000/.well-known/agent-card.json"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "DISCOVERED",
    "rejectionReasonCode": "PRIVATE_OR_LOCAL_ENDPOINT",
    "rejectionReason": "all declared endpoints are loopback or private-network targets",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "PRIVATE_OR_LOCAL_ENDPOINT",
        "reason": "all declared endpoints are loopback or private-network targets"
      }
    ]
  },
  {
    "key": "97-1365",
    "chainId": 97,
    "tokenId": "1365",
    "name": "cmc-disciplined-trader",
    "owner": "0xcd361a2b48cc8c2be9578815b00afa338d7f376f",
    "thirdParty": true,
    "categories": [
      "grid"
    ],
    "declaredProtocols": [],
    "declaredEndpoints": [],
    "finalState": "REJECTED",
    "highestStageReached": "DISCOVERED",
    "rejectionReasonCode": "NO_ENDPOINT",
    "rejectionReason": "no HTTP(S) endpoint declared in metadata",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "NO_ENDPOINT",
        "reason": "no HTTP(S) endpoint declared in metadata"
      }
    ]
  },
  {
    "key": "97-137",
    "chainId": 97,
    "tokenId": "137",
    "name": "PortfolioGuardian",
    "owner": "0x669745979a8b584304d535d13727915d2cf532e4",
    "thirdParty": true,
    "categories": [
      "rebalancing",
      "health"
    ],
    "declaredProtocols": [
      "A2A"
    ],
    "declaredEndpoints": [
      "https://portfolioguardian.agentx.network/.well-known/agent-card.json"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "METADATA_VALID",
    "rejectionReasonCode": "DEAD_DOMAIN",
    "rejectionReason": "endpoint probed under the safety policy and did not respond as a live service",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "METADATA_VALID",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-58-09-394Z-raw.json"
      },
      {
        "from": "METADATA_VALID",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-58-09-394Z-raw.json",
        "reasonCode": "DEAD_DOMAIN",
        "reason": "endpoint probed under the safety policy and did not respond as a live service"
      }
    ]
  },
  {
    "key": "97-1455",
    "chainId": 97,
    "tokenId": "1455",
    "name": "cascade-predator",
    "owner": "0x3660362beb3a95ce16d981e7d30e1e025e741393",
    "thirdParty": true,
    "categories": [
      "health"
    ],
    "declaredProtocols": [],
    "declaredEndpoints": [
      "http://localhost:8003/skill/scan/{token}",
      "http://localhost:8003/erc8183/status"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "DISCOVERED",
    "rejectionReasonCode": "PRIVATE_OR_LOCAL_ENDPOINT",
    "rejectionReason": "all declared endpoints are loopback or private-network targets",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "PRIVATE_OR_LOCAL_ENDPOINT",
        "reason": "all declared endpoints are loopback or private-network targets"
      }
    ]
  },
  {
    "key": "97-150",
    "chainId": 97,
    "tokenId": "150",
    "name": "Pandora Box",
    "owner": "0xeef274796c0b3db48dafaeeeb2746dc16308985a",
    "thirdParty": true,
    "categories": [
      "none"
    ],
    "declaredProtocols": [
      "OASF"
    ],
    "declaredEndpoints": [
      "https://github.com/agntcy/oasf/"
    ],
    "finalState": "METADATA_VALID",
    "highestStageReached": "METADATA_VALID",
    "rejectionReasonCode": null,
    "rejectionReason": null,
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "METADATA_VALID",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-58-09-394Z-raw.json"
      }
    ]
  },
  {
    "key": "97-1525",
    "chainId": 97,
    "tokenId": "1525",
    "name": "Random RWA Gacha Seller",
    "owner": "0x1ffab27a9133122fcd075c3b50d8b29a99ce0f7e",
    "thirdParty": true,
    "categories": [
      "yield"
    ],
    "declaredProtocols": [],
    "declaredEndpoints": [
      "http://127.0.0.1:8004"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "DISCOVERED",
    "rejectionReasonCode": "PRIVATE_OR_LOCAL_ENDPOINT",
    "rejectionReason": "all declared endpoints are loopback or private-network targets",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "PRIVATE_OR_LOCAL_ENDPOINT",
        "reason": "all declared endpoints are loopback or private-network targets"
      }
    ]
  },
  {
    "key": "97-1702",
    "chainId": 97,
    "tokenId": "1702",
    "name": "AgentSentinel Guardian",
    "owner": "0x697c17ba5d8d022631965c8b3653749a1d39c298",
    "thirdParty": true,
    "categories": [
      "health"
    ],
    "declaredProtocols": [
      "MCP"
    ],
    "declaredEndpoints": [
      "https://agentsentinel-guardian.tail2f5a7a.ts.net/mcp"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "REACHABLE",
    "rejectionReasonCode": "NO_PROTOCOL_DETECTED",
    "rejectionReason": "endpoint reachable but no agent protocol (ERC-8183/APEX/A2A/MCP) responded; self-declared protocols do not advance",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "METADATA_VALID",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json"
      },
      {
        "from": "METADATA_VALID",
        "to": "REACHABLE",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json"
      },
      {
        "from": "REACHABLE",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "NO_PROTOCOL_DETECTED",
        "reason": "endpoint reachable but no agent protocol (ERC-8183/APEX/A2A/MCP) responded; self-declared protocols do not advance"
      }
    ]
  },
  {
    "key": "97-1754",
    "chainId": 97,
    "tokenId": "1754",
    "name": "e2e-singleAgent-ms793d4a.agent",
    "owner": "0x351d81d1fc2e0a3629bb5512d991d7907dc40e75",
    "thirdParty": true,
    "categories": [
      "none"
    ],
    "declaredProtocols": [
      "A2A"
    ],
    "declaredEndpoints": [
      "https://platform-backend.dev.termix.live/api/v1/a2a/agents/{agentId}/card"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "DISCOVERED",
    "rejectionReasonCode": "TEMPLATE_ENDPOINT",
    "rejectionReason": "declared endpoint contains an unsubstituted template placeholder",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "TEMPLATE_ENDPOINT",
        "reason": "declared endpoint contains an unsubstituted template placeholder"
      }
    ]
  },
  {
    "key": "97-1755",
    "chainId": 97,
    "tokenId": "1755",
    "name": "studio-agent",
    "owner": "0x83f1f26484b7e6bd02e1fae91830546a5fb2fda9",
    "thirdParty": true,
    "categories": [
      "none"
    ],
    "declaredProtocols": [
      "A2A"
    ],
    "declaredEndpoints": [
      "https://selleragent.example.com/mcp/.well-known/agent-card.json"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "DISCOVERED",
    "rejectionReasonCode": "DEAD_DOMAIN",
    "rejectionReason": "declared endpoint uses a reserved .example domain that cannot resolve",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "DEAD_DOMAIN",
        "reason": "declared endpoint uses a reserved .example domain that cannot resolve"
      }
    ]
  },
  {
    "key": "97-1756",
    "chainId": 97,
    "tokenId": "1756",
    "name": "Global Score Agent",
    "owner": "0x6bda91d3fee5fd69a1202fe851dc37d3a3a1291e",
    "thirdParty": true,
    "categories": [
      "none"
    ],
    "declaredProtocols": [
      "A2A"
    ],
    "declaredEndpoints": [
      "https://static.okx.com/cdn/web3/wallet/marketplace/headimages/agent/card/7fb6b01c-e59a-4f7f-a3e6-96e39e934abd.json/.well-known/agent-card.json"
    ],
    "finalState": "METADATA_VALID",
    "highestStageReached": "METADATA_VALID",
    "rejectionReasonCode": null,
    "rejectionReason": null,
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "METADATA_VALID",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json"
      }
    ]
  },
  {
    "key": "97-1758",
    "chainId": 97,
    "tokenId": "1758",
    "name": "studio-agent",
    "owner": "0xc1b1e7b79515aa5d7018e2ea2f48037d79b1500c",
    "thirdParty": true,
    "categories": [
      "none"
    ],
    "declaredProtocols": [
      "A2A"
    ],
    "declaredEndpoints": [
      "https://bedrock-agentcore.us-east-1.amazonaws.com/runtimes/arn%3Aaws%3Abedrock-agentcore%3Aus-east-1%3A201243086760%3Aruntime%2Ftfpagent-6w4V3q6qFJ/invocations/.well-known/agent-card.json?qualifier=DEFAULT"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "REACHABLE",
    "rejectionReasonCode": "NO_PROTOCOL_DETECTED",
    "rejectionReason": "endpoint reachable but no agent protocol (ERC-8183/APEX/A2A/MCP) responded; self-declared protocols do not advance",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "METADATA_VALID",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json"
      },
      {
        "from": "METADATA_VALID",
        "to": "REACHABLE",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json"
      },
      {
        "from": "REACHABLE",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "NO_PROTOCOL_DETECTED",
        "reason": "endpoint reachable but no agent protocol (ERC-8183/APEX/A2A/MCP) responded; self-declared protocols do not advance"
      }
    ]
  },
  {
    "key": "97-1759",
    "chainId": 97,
    "tokenId": "1759",
    "name": "e2e-jrn1-msd1wnr8.agent",
    "owner": "0x8ca94f61d39b82a8957d243f3e5516109065f440",
    "thirdParty": true,
    "categories": [
      "none"
    ],
    "declaredProtocols": [
      "A2A"
    ],
    "declaredEndpoints": [
      "https://platform-backend.dev.termix.live/api/v1/a2a/agents/{agentId}/card"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "DISCOVERED",
    "rejectionReasonCode": "TEMPLATE_ENDPOINT",
    "rejectionReason": "declared endpoint contains an unsubstituted template placeholder",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "TEMPLATE_ENDPOINT",
        "reason": "declared endpoint contains an unsubstituted template placeholder"
      }
    ]
  },
  {
    "key": "97-1760",
    "chainId": 97,
    "tokenId": "1760",
    "name": "e2e-jrn1-msd2dfzt.agent",
    "owner": "0x2e32708c0174428045086d005396af1f22e16531",
    "thirdParty": true,
    "categories": [
      "none"
    ],
    "declaredProtocols": [
      "A2A"
    ],
    "declaredEndpoints": [
      "https://platform-backend.dev.termix.live/api/v1/a2a/agents/{agentId}/card"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "DISCOVERED",
    "rejectionReasonCode": "TEMPLATE_ENDPOINT",
    "rejectionReason": "declared endpoint contains an unsubstituted template placeholder",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "TEMPLATE_ENDPOINT",
        "reason": "declared endpoint contains an unsubstituted template placeholder"
      }
    ]
  },
  {
    "key": "97-1761",
    "chainId": 97,
    "tokenId": "1761",
    "name": "e2e-jrn1-mse2c71e.agent",
    "owner": "0x70815847eadb3fce178ccec9cf2c6df67a3c850a",
    "thirdParty": true,
    "categories": [
      "none"
    ],
    "declaredProtocols": [
      "A2A"
    ],
    "declaredEndpoints": [
      "https://platform-backend.dev.termix.live/api/v1/a2a/agents/{agentId}/card"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "DISCOVERED",
    "rejectionReasonCode": "TEMPLATE_ENDPOINT",
    "rejectionReason": "declared endpoint contains an unsubstituted template placeholder",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "TEMPLATE_ENDPOINT",
        "reason": "declared endpoint contains an unsubstituted template placeholder"
      }
    ]
  },
  {
    "key": "97-1762",
    "chainId": 97,
    "tokenId": "1762",
    "name": "e2e-jrn1-mse504a8.agent",
    "owner": "0x020fb12795c7b56fa5f60f5732480b157cb543b1",
    "thirdParty": true,
    "categories": [
      "none"
    ],
    "declaredProtocols": [
      "A2A"
    ],
    "declaredEndpoints": [
      "https://platform-backend.dev.termix.live/api/v1/a2a/agents/{agentId}/card"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "DISCOVERED",
    "rejectionReasonCode": "TEMPLATE_ENDPOINT",
    "rejectionReason": "declared endpoint contains an unsubstituted template placeholder",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "TEMPLATE_ENDPOINT",
        "reason": "declared endpoint contains an unsubstituted template placeholder"
      }
    ]
  },
  {
    "key": "97-1763",
    "chainId": 97,
    "tokenId": "1763",
    "name": "e2e-jrn1-mse9tl3r.agent",
    "owner": "0x2ff8104884dd9781915f6ac4a90955d627aa71b4",
    "thirdParty": true,
    "categories": [
      "none"
    ],
    "declaredProtocols": [
      "A2A"
    ],
    "declaredEndpoints": [
      "https://platform-backend.dev.termix.live/api/v1/a2a/agents/{agentId}/card"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "DISCOVERED",
    "rejectionReasonCode": "TEMPLATE_ENDPOINT",
    "rejectionReason": "declared endpoint contains an unsubstituted template placeholder",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "TEMPLATE_ENDPOINT",
        "reason": "declared endpoint contains an unsubstituted template placeholder"
      }
    ]
  },
  {
    "key": "97-1764",
    "chainId": 97,
    "tokenId": "1764",
    "name": "studio-agent",
    "owner": "0xf75cfe97506a39017ca68425a713037202442769",
    "thirdParty": true,
    "categories": [
      "none"
    ],
    "declaredProtocols": [
      "A2A"
    ],
    "declaredEndpoints": [
      "https://bedrock-agentcore.us-east-1.amazonaws.com/runtimes/arn%3Aaws%3Abedrock-agentcore%3Aus-east-1%3A201243086760%3Aruntime%2Ftfaagent-CqA9zM83Td/invocations/.well-known/agent-card.json?qualifier=DEFAULT"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "REACHABLE",
    "rejectionReasonCode": "NO_PROTOCOL_DETECTED",
    "rejectionReason": "endpoint reachable but no agent protocol (ERC-8183/APEX/A2A/MCP) responded; self-declared protocols do not advance",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "METADATA_VALID",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json"
      },
      {
        "from": "METADATA_VALID",
        "to": "REACHABLE",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json"
      },
      {
        "from": "REACHABLE",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "NO_PROTOCOL_DETECTED",
        "reason": "endpoint reachable but no agent protocol (ERC-8183/APEX/A2A/MCP) responded; self-declared protocols do not advance"
      }
    ]
  },
  {
    "key": "97-1766",
    "chainId": 97,
    "tokenId": "1766",
    "name": "e2e-jrn1-msegxv5l.agent",
    "owner": "0x17bdb51bed17d1c29b0595e11c03951ca4185dc6",
    "thirdParty": true,
    "categories": [
      "none"
    ],
    "declaredProtocols": [
      "A2A"
    ],
    "declaredEndpoints": [
      "https://platform-backend.dev.termix.live/api/v1/a2a/agents/{agentId}/card"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "DISCOVERED",
    "rejectionReasonCode": "TEMPLATE_ENDPOINT",
    "rejectionReason": "declared endpoint contains an unsubstituted template placeholder",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "TEMPLATE_ENDPOINT",
        "reason": "declared endpoint contains an unsubstituted template placeholder"
      }
    ]
  },
  {
    "key": "97-1767",
    "chainId": 97,
    "tokenId": "1767",
    "name": "studio-agent",
    "owner": "0xdbecf5b6cc1542b5e58e5b50dc958faa7e757a85",
    "thirdParty": true,
    "categories": [
      "none"
    ],
    "declaredProtocols": [
      "A2A"
    ],
    "declaredEndpoints": [
      "http://127.0.0.1:9000/.well-known/agent-card.json"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "DISCOVERED",
    "rejectionReasonCode": "PRIVATE_OR_LOCAL_ENDPOINT",
    "rejectionReason": "all declared endpoints are loopback or private-network targets",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "PRIVATE_OR_LOCAL_ENDPOINT",
        "reason": "all declared endpoints are loopback or private-network targets"
      }
    ]
  },
  {
    "key": "97-1768",
    "chainId": 97,
    "tokenId": "1768",
    "name": "yield-rebalancer-agent",
    "owner": "0xd4cc67a17d96051bca0356c4eef3cdf188ebce77",
    "thirdParty": true,
    "categories": [
      "rebalancing",
      "yield"
    ],
    "declaredProtocols": [
      "A2A"
    ],
    "declaredEndpoints": [
      "http://localhost:8010/a2a/.well-known/agent-card.json"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "DISCOVERED",
    "rejectionReasonCode": "PRIVATE_OR_LOCAL_ENDPOINT",
    "rejectionReason": "all declared endpoints are loopback or private-network targets",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "PRIVATE_OR_LOCAL_ENDPOINT",
        "reason": "all declared endpoints are loopback or private-network targets"
      }
    ]
  },
  {
    "key": "97-1769",
    "chainId": 97,
    "tokenId": "1769",
    "name": "e2e-jrn1-msfpso0p.agent",
    "owner": "0x932dfdd0b01e48f15b7682140254fae3276f6dc5",
    "thirdParty": true,
    "categories": [
      "none"
    ],
    "declaredProtocols": [
      "A2A"
    ],
    "declaredEndpoints": [
      "https://platform-backend.dev.termix.live/api/v1/a2a/agents/{agentId}/card"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "DISCOVERED",
    "rejectionReasonCode": "TEMPLATE_ENDPOINT",
    "rejectionReason": "declared endpoint contains an unsubstituted template placeholder",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "TEMPLATE_ENDPOINT",
        "reason": "declared endpoint contains an unsubstituted template placeholder"
      }
    ]
  },
  {
    "key": "97-1770",
    "chainId": 97,
    "tokenId": "1770",
    "name": "e2e-jrn1-msfuuy73.agent",
    "owner": "0xc011a157e2b218deba784c66a71b2bf16e6ca122",
    "thirdParty": true,
    "categories": [
      "none"
    ],
    "declaredProtocols": [
      "A2A"
    ],
    "declaredEndpoints": [
      "https://platform-backend.dev.termix.live/api/v1/a2a/agents/{agentId}/card"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "DISCOVERED",
    "rejectionReasonCode": "TEMPLATE_ENDPOINT",
    "rejectionReason": "declared endpoint contains an unsubstituted template placeholder",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "TEMPLATE_ENDPOINT",
        "reason": "declared endpoint contains an unsubstituted template placeholder"
      }
    ]
  },
  {
    "key": "97-1771",
    "chainId": 97,
    "tokenId": "1771",
    "name": "studio-agent",
    "owner": "0x2b114b7f2aa393326982afa3f684b7c63ae1ee36",
    "thirdParty": true,
    "categories": [
      "none"
    ],
    "declaredProtocols": [
      "A2A"
    ],
    "declaredEndpoints": [
      "https://bedrock-agentcore.us-east-1.amazonaws.com/runtimes/arn%3Aaws%3Abedrock-agentcore%3Aus-east-1%3A201243086760%3Aruntime%2Ftfsagent-5pQjbpE0W8/invocations/.well-known/agent-card.json?qualifier=DEFAULT"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "REACHABLE",
    "rejectionReasonCode": "NO_PROTOCOL_DETECTED",
    "rejectionReason": "endpoint reachable but no agent protocol (ERC-8183/APEX/A2A/MCP) responded; self-declared protocols do not advance",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "METADATA_VALID",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json"
      },
      {
        "from": "METADATA_VALID",
        "to": "REACHABLE",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json"
      },
      {
        "from": "REACHABLE",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "NO_PROTOCOL_DETECTED",
        "reason": "endpoint reachable but no agent protocol (ERC-8183/APEX/A2A/MCP) responded; self-declared protocols do not advance"
      }
    ]
  },
  {
    "key": "97-1772",
    "chainId": 97,
    "tokenId": "1772",
    "name": "studio-agent",
    "owner": "0x1f940bf463aa1afb97113dfcec13b3ad1c9e75c4",
    "thirdParty": true,
    "categories": [
      "none"
    ],
    "declaredProtocols": [
      "A2A"
    ],
    "declaredEndpoints": [
      "https://bnbagent-api.bnbchain.world/v1/rt/01KZAH0RY00BHF3ZX99F6HTTCQ/.well-known/agent-card.json"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "REACHABLE",
    "rejectionReasonCode": "NO_PROTOCOL_DETECTED",
    "rejectionReason": "endpoint reachable but no agent protocol (ERC-8183/APEX/A2A/MCP) responded; self-declared protocols do not advance",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "METADATA_VALID",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json"
      },
      {
        "from": "METADATA_VALID",
        "to": "REACHABLE",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json"
      },
      {
        "from": "REACHABLE",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "NO_PROTOCOL_DETECTED",
        "reason": "endpoint reachable but no agent protocol (ERC-8183/APEX/A2A/MCP) responded; self-declared protocols do not advance"
      }
    ]
  },
  {
    "key": "97-1773",
    "chainId": 97,
    "tokenId": "1773",
    "name": "studio-agent",
    "owner": "0xa17e5b37b8987df7aacd00fe37a64ce9dccd0133",
    "thirdParty": true,
    "categories": [
      "none"
    ],
    "declaredProtocols": [
      "A2A"
    ],
    "declaredEndpoints": [
      "https://bnbagent-api.bnbchain.world/v1/rt/01KZBTZ2A4NRRY71WF8YV4EXXY/a2a/.well-known/agent-card.json"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "REACHABLE",
    "rejectionReasonCode": "NO_PROTOCOL_DETECTED",
    "rejectionReason": "endpoint reachable but no agent protocol (ERC-8183/APEX/A2A/MCP) responded; self-declared protocols do not advance",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "METADATA_VALID",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json"
      },
      {
        "from": "METADATA_VALID",
        "to": "REACHABLE",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json"
      },
      {
        "from": "REACHABLE",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "NO_PROTOCOL_DETECTED",
        "reason": "endpoint reachable but no agent protocol (ERC-8183/APEX/A2A/MCP) responded; self-declared protocols do not advance"
      }
    ]
  },
  {
    "key": "97-1774",
    "chainId": 97,
    "tokenId": "1774",
    "name": "studio-agent",
    "owner": "0xe588cd118a7d960a5f64788ed2f61e873dac97e4",
    "thirdParty": true,
    "categories": [
      "none"
    ],
    "declaredProtocols": [
      "A2A"
    ],
    "declaredEndpoints": [
      "https://bnbagent-api.bnbchain.world/v1/rt/01KZBXKNH3VKHHE3YCH1K496A9/a2a/.well-known/agent-card.json"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "REACHABLE",
    "rejectionReasonCode": "NO_PROTOCOL_DETECTED",
    "rejectionReason": "endpoint reachable but no agent protocol (ERC-8183/APEX/A2A/MCP) responded; self-declared protocols do not advance",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "METADATA_VALID",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json"
      },
      {
        "from": "METADATA_VALID",
        "to": "REACHABLE",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json"
      },
      {
        "from": "REACHABLE",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "NO_PROTOCOL_DETECTED",
        "reason": "endpoint reachable but no agent protocol (ERC-8183/APEX/A2A/MCP) responded; self-declared protocols do not advance"
      }
    ]
  },
  {
    "key": "97-1775",
    "chainId": 97,
    "tokenId": "1775",
    "name": "studio-agent",
    "owner": "0x037ffbf18df73812ec29d024abb7e79dbb4356c8",
    "thirdParty": true,
    "categories": [
      "none"
    ],
    "declaredProtocols": [
      "A2A"
    ],
    "declaredEndpoints": [
      "https://bnbagent-api.bnbchain.world/v1/rt/01KZBXTNSPVX052KK69RPWJMN8/a2a/.well-known/agent-card.json"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "REACHABLE",
    "rejectionReasonCode": "NO_PROTOCOL_DETECTED",
    "rejectionReason": "endpoint reachable but no agent protocol (ERC-8183/APEX/A2A/MCP) responded; self-declared protocols do not advance",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "METADATA_VALID",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json"
      },
      {
        "from": "METADATA_VALID",
        "to": "REACHABLE",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json"
      },
      {
        "from": "REACHABLE",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "NO_PROTOCOL_DETECTED",
        "reason": "endpoint reachable but no agent protocol (ERC-8183/APEX/A2A/MCP) responded; self-declared protocols do not advance"
      }
    ]
  },
  {
    "key": "97-1777",
    "chainId": 97,
    "tokenId": "1777",
    "name": "grid-trading-agent",
    "owner": "0x3c0051722f04cd25563c250a62f8fcb88e4b88d6",
    "thirdParty": true,
    "categories": [
      "grid"
    ],
    "declaredProtocols": [
      "MCP",
      "Web"
    ],
    "declaredEndpoints": [
      "https://grid-trading-agent-demo.vercel.app/mcp",
      "https://grid-trading-agent-demo.vercel.app/"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "REACHABLE",
    "rejectionReasonCode": "NO_PROTOCOL_DETECTED",
    "rejectionReason": "endpoint reachable but no agent protocol (ERC-8183/APEX/A2A/MCP) responded; self-declared protocols do not advance",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "METADATA_VALID",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json"
      },
      {
        "from": "METADATA_VALID",
        "to": "REACHABLE",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json"
      },
      {
        "from": "REACHABLE",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "NO_PROTOCOL_DETECTED",
        "reason": "endpoint reachable but no agent protocol (ERC-8183/APEX/A2A/MCP) responded; self-declared protocols do not advance"
      }
    ]
  },
  {
    "key": "97-1778",
    "chainId": 97,
    "tokenId": "1778",
    "name": "health-factor-agent",
    "owner": "0x3c0051722f04cd25563c250a62f8fcb88e4b88d6",
    "thirdParty": true,
    "categories": [
      "rebalancing",
      "health"
    ],
    "declaredProtocols": [
      "MCP",
      "Web"
    ],
    "declaredEndpoints": [
      "https://health-factor-agent-demo.vercel.app/mcp",
      "https://health-factor-agent-demo.vercel.app/"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "REACHABLE",
    "rejectionReasonCode": "NO_PROTOCOL_DETECTED",
    "rejectionReason": "endpoint reachable but no agent protocol (ERC-8183/APEX/A2A/MCP) responded; self-declared protocols do not advance",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "METADATA_VALID",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json"
      },
      {
        "from": "METADATA_VALID",
        "to": "REACHABLE",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json"
      },
      {
        "from": "REACHABLE",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "NO_PROTOCOL_DETECTED",
        "reason": "endpoint reachable but no agent protocol (ERC-8183/APEX/A2A/MCP) responded; self-declared protocols do not advance"
      }
    ]
  },
  {
    "key": "97-1779",
    "chainId": 97,
    "tokenId": "1779",
    "name": "yield-agent",
    "owner": "0x3c0051722f04cd25563c250a62f8fcb88e4b88d6",
    "thirdParty": true,
    "categories": [
      "rebalancing",
      "yield",
      "health"
    ],
    "declaredProtocols": [
      "MCP",
      "Web"
    ],
    "declaredEndpoints": [
      "https://yield-agent-demo.vercel.app/mcp",
      "https://yield-agent-demo.vercel.app/"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "REACHABLE",
    "rejectionReasonCode": "NO_PROTOCOL_DETECTED",
    "rejectionReason": "endpoint reachable but no agent protocol (ERC-8183/APEX/A2A/MCP) responded; self-declared protocols do not advance",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "METADATA_VALID",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json"
      },
      {
        "from": "METADATA_VALID",
        "to": "REACHABLE",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json"
      },
      {
        "from": "REACHABLE",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "NO_PROTOCOL_DETECTED",
        "reason": "endpoint reachable but no agent protocol (ERC-8183/APEX/A2A/MCP) responded; self-declared protocols do not advance"
      }
    ]
  },
  {
    "key": "97-1780",
    "chainId": 97,
    "tokenId": "1780",
    "name": "studio-agent",
    "owner": "0x748e2c3b97d238a5c3e63cd6ddd59dda41233f22",
    "thirdParty": true,
    "categories": [
      "none"
    ],
    "declaredProtocols": [
      "A2A"
    ],
    "declaredEndpoints": [
      "https://bnbagent-api.bnbchain.world/v1/rt/01KZD9DT5V0FSG5CWK05T5W6HQ/.well-known/agent-card.json"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "REACHABLE",
    "rejectionReasonCode": "NO_PROTOCOL_DETECTED",
    "rejectionReason": "endpoint reachable but no agent protocol (ERC-8183/APEX/A2A/MCP) responded; self-declared protocols do not advance",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "METADATA_VALID",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json"
      },
      {
        "from": "METADATA_VALID",
        "to": "REACHABLE",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json"
      },
      {
        "from": "REACHABLE",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "NO_PROTOCOL_DETECTED",
        "reason": "endpoint reachable but no agent protocol (ERC-8183/APEX/A2A/MCP) responded; self-declared protocols do not advance"
      }
    ]
  },
  {
    "key": "97-1784",
    "chainId": 97,
    "tokenId": "1784",
    "name": "AgentGovernor/FeeOptimizer",
    "owner": "0x3a56452944619a2b2a674e8f2a8c49103420fa73",
    "thirdParty": true,
    "categories": [
      "rebalancing",
      "yield"
    ],
    "declaredProtocols": [],
    "declaredEndpoints": [],
    "finalState": "REJECTED",
    "highestStageReached": "DISCOVERED",
    "rejectionReasonCode": "NO_ENDPOINT",
    "rejectionReason": "no HTTP(S) endpoint declared in metadata",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "NO_ENDPOINT",
        "reason": "no HTTP(S) endpoint declared in metadata"
      }
    ]
  },
  {
    "key": "97-1791",
    "chainId": 97,
    "tokenId": "1791",
    "name": "GuardRail GridBot",
    "owner": "0xa847f3bbf69e8a888b59bc8729ce787e0db5be97",
    "thirdParty": true,
    "categories": [
      "grid"
    ],
    "declaredProtocols": [],
    "declaredEndpoints": [],
    "finalState": "REJECTED",
    "highestStageReached": "DISCOVERED",
    "rejectionReasonCode": "NO_ENDPOINT",
    "rejectionReason": "no HTTP(S) endpoint declared in metadata",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "NO_ENDPOINT",
        "reason": "no HTTP(S) endpoint declared in metadata"
      }
    ]
  },
  {
    "key": "97-1792",
    "chainId": 97,
    "tokenId": "1792",
    "name": "GuardRail Yield Router",
    "owner": "0xa847f3bbf69e8a888b59bc8729ce787e0db5be97",
    "thirdParty": true,
    "categories": [
      "yield"
    ],
    "declaredProtocols": [],
    "declaredEndpoints": [],
    "finalState": "REJECTED",
    "highestStageReached": "DISCOVERED",
    "rejectionReasonCode": "NO_ENDPOINT",
    "rejectionReason": "no HTTP(S) endpoint declared in metadata",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "NO_ENDPOINT",
        "reason": "no HTTP(S) endpoint declared in metadata"
      }
    ]
  },
  {
    "key": "97-1793",
    "chainId": 97,
    "tokenId": "1793",
    "name": "GuardRail Health Guard",
    "owner": "0xa847f3bbf69e8a888b59bc8729ce787e0db5be97",
    "thirdParty": true,
    "categories": [
      "health"
    ],
    "declaredProtocols": [],
    "declaredEndpoints": [],
    "finalState": "REJECTED",
    "highestStageReached": "DISCOVERED",
    "rejectionReasonCode": "NO_ENDPOINT",
    "rejectionReason": "no HTTP(S) endpoint declared in metadata",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "NO_ENDPOINT",
        "reason": "no HTTP(S) endpoint declared in metadata"
      }
    ]
  },
  {
    "key": "97-1796",
    "chainId": 97,
    "tokenId": "1796",
    "name": "fxagent",
    "owner": "0x20f1ca5d1e5a3ee94c29dbf95e6bf6cea6a8d64b",
    "thirdParty": true,
    "categories": [
      "none"
    ],
    "declaredProtocols": [
      "A2A"
    ],
    "declaredEndpoints": [
      "http://localhost:9000/.well-known/agent-card.json"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "DISCOVERED",
    "rejectionReasonCode": "PRIVATE_OR_LOCAL_ENDPOINT",
    "rejectionReason": "all declared endpoints are loopback or private-network targets",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "PRIVATE_OR_LOCAL_ENDPOINT",
        "reason": "all declared endpoints are loopback or private-network targets"
      }
    ]
  },
  {
    "key": "97-1797",
    "chainId": 97,
    "tokenId": "1797",
    "name": "test.agent",
    "owner": "0x3484cc21acdae7b430389ebc071b3ed6fd94ccd9",
    "thirdParty": true,
    "categories": [
      "none"
    ],
    "declaredProtocols": [
      "A2A"
    ],
    "declaredEndpoints": [
      "https://platform-backend-bnb8183.dev.termix.live/api/v1/a2a/agents/{agentId}/card"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "DISCOVERED",
    "rejectionReasonCode": "TEMPLATE_ENDPOINT",
    "rejectionReason": "declared endpoint contains an unsubstituted template placeholder",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "TEMPLATE_ENDPOINT",
        "reason": "declared endpoint contains an unsubstituted template placeholder"
      }
    ]
  },
  {
    "key": "97-1798",
    "chainId": 97,
    "tokenId": "1798",
    "name": "Portfolio Reporter v1",
    "owner": "0x3c8176953eadbee7b9bf8c6a5d1cf1153d924e11",
    "thirdParty": true,
    "categories": [
      "rebalancing"
    ],
    "declaredProtocols": [],
    "declaredEndpoints": [],
    "finalState": "REJECTED",
    "highestStageReached": "DISCOVERED",
    "rejectionReasonCode": "NO_ENDPOINT",
    "rejectionReason": "no HTTP(S) endpoint declared in metadata",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "NO_ENDPOINT",
        "reason": "no HTTP(S) endpoint declared in metadata"
      }
    ]
  },
  {
    "key": "97-1799",
    "chainId": 97,
    "tokenId": "1799",
    "name": "rej-prov-1786437907.agent",
    "owner": "0x20a8078506d7a906e7f6a1914aa3987b766777e6",
    "thirdParty": true,
    "categories": [
      "none"
    ],
    "declaredProtocols": [
      "A2A"
    ],
    "declaredEndpoints": [
      "https://platform-backend-bnb8183-self.dev.termix.live/api/v1/a2a/agents/{agentId}/card"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "DISCOVERED",
    "rejectionReasonCode": "TEMPLATE_ENDPOINT",
    "rejectionReason": "declared endpoint contains an unsubstituted template placeholder",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "TEMPLATE_ENDPOINT",
        "reason": "declared endpoint contains an unsubstituted template placeholder"
      }
    ]
  },
  {
    "key": "97-1800",
    "chainId": 97,
    "tokenId": "1800",
    "name": "rej-buy-1786437907.agent",
    "owner": "0xbee646d6435c5ebb0a5f2992c0e77648c9c6f56b",
    "thirdParty": true,
    "categories": [
      "none"
    ],
    "declaredProtocols": [
      "A2A"
    ],
    "declaredEndpoints": [
      "https://platform-backend-bnb8183-self.dev.termix.live/api/v1/a2a/agents/{agentId}/card"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "DISCOVERED",
    "rejectionReasonCode": "TEMPLATE_ENDPOINT",
    "rejectionReason": "declared endpoint contains an unsubstituted template placeholder",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "TEMPLATE_ENDPOINT",
        "reason": "declared endpoint contains an unsubstituted template placeholder"
      }
    ]
  },
  {
    "key": "97-1801",
    "chainId": 97,
    "tokenId": "1801",
    "name": "rej-prov-1786438012.agent",
    "owner": "0x20a8078506d7a906e7f6a1914aa3987b766777e6",
    "thirdParty": true,
    "categories": [
      "none"
    ],
    "declaredProtocols": [
      "A2A"
    ],
    "declaredEndpoints": [
      "https://platform-backend-bnb8183-self.dev.termix.live/api/v1/a2a/agents/{agentId}/card"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "DISCOVERED",
    "rejectionReasonCode": "TEMPLATE_ENDPOINT",
    "rejectionReason": "declared endpoint contains an unsubstituted template placeholder",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "TEMPLATE_ENDPOINT",
        "reason": "declared endpoint contains an unsubstituted template placeholder"
      }
    ]
  },
  {
    "key": "97-1802",
    "chainId": 97,
    "tokenId": "1802",
    "name": "rej-buy-1786438012.agent",
    "owner": "0xbee646d6435c5ebb0a5f2992c0e77648c9c6f56b",
    "thirdParty": true,
    "categories": [
      "none"
    ],
    "declaredProtocols": [
      "A2A"
    ],
    "declaredEndpoints": [
      "https://platform-backend-bnb8183-self.dev.termix.live/api/v1/a2a/agents/{agentId}/card"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "DISCOVERED",
    "rejectionReasonCode": "TEMPLATE_ENDPOINT",
    "rejectionReason": "declared endpoint contains an unsubstituted template placeholder",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-41-16-090Z-raw.json",
        "reasonCode": "TEMPLATE_ENDPOINT",
        "reason": "declared endpoint contains an unsubstituted template placeholder"
      }
    ]
  },
  {
    "key": "97-1803",
    "chainId": 97,
    "tokenId": "1803",
    "name": "jack.agent",
    "owner": "0x3484cc21acdae7b430389ebc071b3ed6fd94ccd9",
    "thirdParty": true,
    "categories": [
      "none"
    ],
    "declaredProtocols": [
      "A2A"
    ],
    "declaredEndpoints": [
      "https://platform-backend-bnb8183-self.dev.termix.live/api/v1/a2a/agents/{agentId}/card"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "DISCOVERED",
    "rejectionReasonCode": "TEMPLATE_ENDPOINT",
    "rejectionReason": "declared endpoint contains an unsubstituted template placeholder",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T21-50-47-380Z-raw.json",
        "reasonCode": "TEMPLATE_ENDPOINT",
        "reason": "declared endpoint contains an unsubstituted template placeholder"
      }
    ]
  },
  {
    "key": "97-1804",
    "chainId": 97,
    "tokenId": "1804",
    "name": "RangeGuard",
    "owner": "0xd30bbb80c863c9b94622ef92337aad65148d2ec3",
    "thirdParty": true,
    "categories": [
      "rebalancing"
    ],
    "declaredProtocols": [
      "Web"
    ],
    "declaredEndpoints": [
      "https://mandate-bnb-agent.vercel.app/api/health"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "REACHABLE",
    "rejectionReasonCode": "NO_PROTOCOL_DETECTED",
    "rejectionReason": "endpoint reachable but no agent protocol (ERC-8183/APEX/A2A/MCP) responded; self-declared protocols do not advance",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "METADATA_VALID",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T21-50-47-380Z-raw.json"
      },
      {
        "from": "METADATA_VALID",
        "to": "REACHABLE",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T21-50-47-380Z-raw.json"
      },
      {
        "from": "REACHABLE",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T21-50-47-380Z-raw.json",
        "reasonCode": "NO_PROTOCOL_DETECTED",
        "reason": "endpoint reachable but no agent protocol (ERC-8183/APEX/A2A/MCP) responded; self-declared protocols do not advance"
      }
    ]
  },
  {
    "key": "97-1805",
    "chainId": 97,
    "tokenId": "1805",
    "name": "GridPilot",
    "owner": "0xd30bbb80c863c9b94622ef92337aad65148d2ec3",
    "thirdParty": true,
    "categories": [
      "grid"
    ],
    "declaredProtocols": [
      "Web"
    ],
    "declaredEndpoints": [
      "https://mandate-bnb-agent.vercel.app/api/health"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "REACHABLE",
    "rejectionReasonCode": "NO_PROTOCOL_DETECTED",
    "rejectionReason": "endpoint reachable but no agent protocol (ERC-8183/APEX/A2A/MCP) responded; self-declared protocols do not advance",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "METADATA_VALID",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T21-50-47-380Z-raw.json"
      },
      {
        "from": "METADATA_VALID",
        "to": "REACHABLE",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T21-50-47-380Z-raw.json"
      },
      {
        "from": "REACHABLE",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T21-50-47-380Z-raw.json",
        "reasonCode": "NO_PROTOCOL_DETECTED",
        "reason": "endpoint reachable but no agent protocol (ERC-8183/APEX/A2A/MCP) responded; self-declared protocols do not advance"
      }
    ]
  },
  {
    "key": "97-1806",
    "chainId": 97,
    "tokenId": "1806",
    "name": "YieldRoute",
    "owner": "0xd30bbb80c863c9b94622ef92337aad65148d2ec3",
    "thirdParty": true,
    "categories": [
      "yield"
    ],
    "declaredProtocols": [
      "Web"
    ],
    "declaredEndpoints": [
      "https://mandate-bnb-agent.vercel.app/api/health"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "REACHABLE",
    "rejectionReasonCode": "NO_PROTOCOL_DETECTED",
    "rejectionReason": "endpoint reachable but no agent protocol (ERC-8183/APEX/A2A/MCP) responded; self-declared protocols do not advance",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "METADATA_VALID",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T21-50-47-380Z-raw.json"
      },
      {
        "from": "METADATA_VALID",
        "to": "REACHABLE",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T21-50-47-380Z-raw.json"
      },
      {
        "from": "REACHABLE",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T21-50-47-380Z-raw.json",
        "reasonCode": "NO_PROTOCOL_DETECTED",
        "reason": "endpoint reachable but no agent protocol (ERC-8183/APEX/A2A/MCP) responded; self-declared protocols do not advance"
      }
    ]
  },
  {
    "key": "97-1807",
    "chainId": 97,
    "tokenId": "1807",
    "name": "LiqShield",
    "owner": "0xd30bbb80c863c9b94622ef92337aad65148d2ec3",
    "thirdParty": true,
    "categories": [
      "health"
    ],
    "declaredProtocols": [
      "Web"
    ],
    "declaredEndpoints": [
      "https://mandate-bnb-agent.vercel.app/api/health"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "REACHABLE",
    "rejectionReasonCode": "NO_PROTOCOL_DETECTED",
    "rejectionReason": "endpoint reachable but no agent protocol (ERC-8183/APEX/A2A/MCP) responded; self-declared protocols do not advance",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "METADATA_VALID",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T21-50-47-380Z-raw.json"
      },
      {
        "from": "METADATA_VALID",
        "to": "REACHABLE",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T21-50-47-380Z-raw.json"
      },
      {
        "from": "REACHABLE",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T21-50-47-380Z-raw.json",
        "reasonCode": "NO_PROTOCOL_DETECTED",
        "reason": "endpoint reachable but no agent protocol (ERC-8183/APEX/A2A/MCP) responded; self-declared protocols do not advance"
      }
    ]
  },
  {
    "key": "97-1809",
    "chainId": 97,
    "tokenId": "1809",
    "name": "Atelo Reference Agent (Atelo-owned, not third-party)",
    "owner": "0xEc6816734AD21Fc90e32d8cd35C5a1EF665F7c8C",
    "thirdParty": false,
    "categories": [
      "rebalancing",
      "grid",
      "yield",
      "health"
    ],
    "declaredProtocols": [
      "ERC-8183"
    ],
    "declaredEndpoints": [
      "https://<ephemeral-tunnel>/erc8183/negotiate"
    ],
    "finalState": "TEST_JOB_PASSED",
    "highestStageReached": "TEST_JOB_PASSED",
    "rejectionReasonCode": null,
    "rejectionReason": null,
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "METADATA_VALID",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/e5-lifecycle-settled-2026-08-12T18-43-11-624Z.json"
      },
      {
        "from": "METADATA_VALID",
        "to": "REACHABLE",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/e5-lifecycle-settled-2026-08-12T18-43-11-624Z.json"
      },
      {
        "from": "REACHABLE",
        "to": "PROTOCOL_COMPATIBLE",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/e5-lifecycle-settled-2026-08-12T18-43-11-624Z.json"
      },
      {
        "from": "PROTOCOL_COMPATIBLE",
        "to": "TEST_JOB_PASSED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/e5-lifecycle-settled-2026-08-12T18-43-11-624Z.json"
      }
    ]
  },
  {
    "key": "97-247",
    "chainId": 97,
    "tokenId": "247",
    "name": "Public Weather Agent",
    "owner": "0x3a74813833a885fbc67ace429077f6578bcbb0e0",
    "thirdParty": true,
    "categories": [
      "none"
    ],
    "declaredProtocols": [
      "A2A",
      "Web"
    ],
    "declaredEndpoints": [
      "https://www.testnet.app.bitagent.io/aip/erc8004:weather_public/.well-known/agent-card.json",
      "https://www.testnet.app.bitagent.io/aip/erc8004:weather_public"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "REACHABLE",
    "rejectionReasonCode": "NO_PROTOCOL_DETECTED",
    "rejectionReason": "endpoint reachable but no agent protocol (ERC-8183/APEX/A2A/MCP) responded; self-declared protocols do not advance",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "METADATA_VALID",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-58-09-394Z-raw.json"
      },
      {
        "from": "METADATA_VALID",
        "to": "REACHABLE",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-58-09-394Z-raw.json"
      },
      {
        "from": "REACHABLE",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-58-09-394Z-raw.json",
        "reasonCode": "NO_PROTOCOL_DETECTED",
        "reason": "endpoint reachable but no agent protocol (ERC-8183/APEX/A2A/MCP) responded; self-declared protocols do not advance"
      }
    ]
  },
  {
    "key": "97-248",
    "chainId": 97,
    "tokenId": "248",
    "name": "Private Calculator Agent",
    "owner": "0x88ae7cc43eb8f17f0280a3246195e9667796740c",
    "thirdParty": true,
    "categories": [
      "none"
    ],
    "declaredProtocols": [
      "A2A",
      "Web"
    ],
    "declaredEndpoints": [
      "https://www.testnet.app.bitagent.io/aip/erc8004:calculator_private/.well-known/agent-card.json",
      "https://www.testnet.app.bitagent.io/aip/erc8004:calculator_private"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "REACHABLE",
    "rejectionReasonCode": "NO_PROTOCOL_DETECTED",
    "rejectionReason": "endpoint reachable but no agent protocol (ERC-8183/APEX/A2A/MCP) responded; self-declared protocols do not advance",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "METADATA_VALID",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-58-09-394Z-raw.json"
      },
      {
        "from": "METADATA_VALID",
        "to": "REACHABLE",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-58-09-394Z-raw.json"
      },
      {
        "from": "REACHABLE",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-58-09-394Z-raw.json",
        "reasonCode": "NO_PROTOCOL_DETECTED",
        "reason": "endpoint reachable but no agent protocol (ERC-8183/APEX/A2A/MCP) responded; self-declared protocols do not advance"
      }
    ]
  },
  {
    "key": "97-269",
    "chainId": 97,
    "tokenId": "269",
    "name": "EcoClaw Climate Agent",
    "owner": "0xa89e30b29ae02a67ce4aa1d6da594f00e0aab9bd",
    "thirdParty": true,
    "categories": [
      "none"
    ],
    "declaredProtocols": [
      "A2A",
      "Web"
    ],
    "declaredEndpoints": [
      "https://www.testnet.app.bitagent.io/aip/erc8004:ecoclaw_climate/.well-known/agent-card.json",
      "https://www.testnet.app.bitagent.io/aip/erc8004:ecoclaw_climate"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "REACHABLE",
    "rejectionReasonCode": "NO_PROTOCOL_DETECTED",
    "rejectionReason": "endpoint reachable but no agent protocol (ERC-8183/APEX/A2A/MCP) responded; self-declared protocols do not advance",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "METADATA_VALID",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-58-09-394Z-raw.json"
      },
      {
        "from": "METADATA_VALID",
        "to": "REACHABLE",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-58-09-394Z-raw.json"
      },
      {
        "from": "REACHABLE",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-58-09-394Z-raw.json",
        "reasonCode": "NO_PROTOCOL_DETECTED",
        "reason": "endpoint reachable but no agent protocol (ERC-8183/APEX/A2A/MCP) responded; self-declared protocols do not advance"
      }
    ]
  },
  {
    "key": "97-388",
    "chainId": 97,
    "tokenId": "388",
    "name": "Agent Test 1",
    "owner": "0x527f61c212805a1019a662a0462dbf3bd7980571",
    "thirdParty": true,
    "categories": [
      "none"
    ],
    "declaredProtocols": [
      "MCP",
      "A2A",
      "OASF",
      "Web",
      "Email"
    ],
    "declaredEndpoints": [
      "https://agent.octopurrr.com/.well-known/agent-card.json",
      "https://mcp.octopurrr.com/",
      "https://octopurrr.com/agents/octopurrbot"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "METADATA_VALID",
    "rejectionReasonCode": "DEAD_DOMAIN",
    "rejectionReason": "endpoint probed under the safety policy and did not respond as a live service",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "METADATA_VALID",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-58-09-394Z-raw.json"
      },
      {
        "from": "METADATA_VALID",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-58-09-394Z-raw.json",
        "reasonCode": "DEAD_DOMAIN",
        "reason": "endpoint probed under the safety policy and did not respond as a live service"
      }
    ]
  },
  {
    "key": "97-391",
    "chainId": 97,
    "tokenId": "391",
    "name": "Agent Test 1",
    "owner": "0x5429e708ab95d76ddd5b1b5ec32e2e16664b00c1",
    "thirdParty": true,
    "categories": [
      "none"
    ],
    "declaredProtocols": [
      "MCP",
      "A2A",
      "OASF",
      "Web",
      "Email"
    ],
    "declaredEndpoints": [
      "https://agent.octopurrr.com/.well-known/agent-card.json",
      "https://mcp.octopurrr.com/",
      "https://octopurrr.com/agents/octopurrbot"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "METADATA_VALID",
    "rejectionReasonCode": "DEAD_DOMAIN",
    "rejectionReason": "endpoint probed under the safety policy and did not respond as a live service",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "METADATA_VALID",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-58-09-394Z-raw.json"
      },
      {
        "from": "METADATA_VALID",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-58-09-394Z-raw.json",
        "reasonCode": "DEAD_DOMAIN",
        "reason": "endpoint probed under the safety policy and did not respond as a live service"
      }
    ]
  },
  {
    "key": "97-397",
    "chainId": 97,
    "tokenId": "397",
    "name": "Yield-Farmer-X1",
    "owner": "0xdf5c40056774dcdc68c4e06270ac861d83b9db41",
    "thirdParty": true,
    "categories": [
      "rebalancing",
      "grid",
      "yield",
      "health"
    ],
    "declaredProtocols": [],
    "declaredEndpoints": [],
    "finalState": "REJECTED",
    "highestStageReached": "DISCOVERED",
    "rejectionReasonCode": "NO_ENDPOINT",
    "rejectionReason": "no HTTP(S) endpoint declared in metadata",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-58-09-394Z-raw.json",
        "reasonCode": "NO_ENDPOINT",
        "reason": "no HTTP(S) endpoint declared in metadata"
      }
    ]
  },
  {
    "key": "97-435",
    "chainId": 97,
    "tokenId": "435",
    "name": "Hertz-1",
    "owner": "0xe947b4f388f0e9c5808e52e92613c36917be7a6b",
    "thirdParty": true,
    "categories": [
      "grid"
    ],
    "declaredProtocols": [],
    "declaredEndpoints": [],
    "finalState": "REJECTED",
    "highestStageReached": "DISCOVERED",
    "rejectionReasonCode": "NO_ENDPOINT",
    "rejectionReason": "no HTTP(S) endpoint declared in metadata",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-58-09-394Z-raw.json",
        "reasonCode": "NO_ENDPOINT",
        "reason": "no HTTP(S) endpoint declared in metadata"
      }
    ]
  },
  {
    "key": "97-610",
    "chainId": 97,
    "tokenId": "610",
    "name": "RPCBeat",
    "owner": "0xba2e781d4c3974c8d2357a7535d8e0d52433c935",
    "thirdParty": true,
    "categories": [
      "none"
    ],
    "declaredProtocols": [
      "MCP",
      "Web"
    ],
    "declaredEndpoints": [
      "https://github.com/Ham3798/rpcBeat"
    ],
    "finalState": "METADATA_VALID",
    "highestStageReached": "METADATA_VALID",
    "rejectionReasonCode": null,
    "rejectionReason": null,
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "METADATA_VALID",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-58-09-394Z-raw.json"
      }
    ]
  },
  {
    "key": "97-738",
    "chainId": 97,
    "tokenId": "738",
    "name": "Meme Image Generator",
    "owner": "0xa50eddab824239d71013002e437b5726235af6ba",
    "thirdParty": true,
    "categories": [
      "none"
    ],
    "declaredProtocols": [
      "A2A",
      "Web"
    ],
    "declaredEndpoints": [
      "http://localhost:8000/agents/meme-image-generator//.well-known/agent-card.json",
      "http://localhost:8000/agents/meme-image-generator/"
    ],
    "finalState": "REJECTED",
    "highestStageReached": "DISCOVERED",
    "rejectionReasonCode": "PRIVATE_OR_LOCAL_ENDPOINT",
    "rejectionReason": "all declared endpoints are loopback or private-network targets",
    "transitions": [
      {
        "from": "DISCOVERED",
        "to": "REJECTED",
        "atUtc": "2026-08-12T00:00:00Z",
        "evidenceRef": "/Users/godson/Desktop/atelo-hub/artifacts/phase-00/raw/agent-details-2026-08-11T23-58-09-394Z-raw.json",
        "reasonCode": "PRIVATE_OR_LOCAL_ENDPOINT",
        "reason": "all declared endpoints are loopback or private-network targets"
      }
    ]
  }
];

export const qualificationReports: RawReport[] = reports;
