// GENERATED by packages/core/scripts/gen-data.mjs — do not edit by hand.
import type { Category } from "../types";
import type { RawRanking } from "../raw";

const data = {
  "grid": {
    "excluded": [
      {
        "key": "97-2500",
        "reason": "below PROTOCOL_COMPATIBLE: state is REACHABLE"
      }
    ],
    "insufficientHistoryWarning": "testnet epoch policy: history capped at \"since first observed, capped at 30 days\"; some agents have less than a full 30d window and are labeled insufficientHistory — short histories are never reported as full-30d figures",
    "observedDurationSeconds": 43017,
    "ranked": [
      {
        "agentId": "97:registry:2200",
        "agentKey": "97-2200",
        "factors": {
          "availability": 1,
          "price": 0.4,
          "reliability": 1,
          "suitability": 1,
          "verifiedPerformance": 0.9
        },
        "firstPartyFallback": false,
        "insufficientHistory": true,
        "label": "ThirdParty Grid Agent (verified)",
        "materialFactors": [
          "grid mean_realized_slippage_bps=5bps over 1 VERIFIED job(s) (third-party marketplace)",
          "suitability=1, price=0.4, availability=1, reliability=1",
          "insufficient history: observed 40017s (< 30d window); testnet epoch capped, not presented as a full-window figure"
        ],
        "sampleCount": 1,
        "score": 0.87,
        "thirdParty": true,
        "verifiedPerformanceProvenance": "third-party",
        "window": {
          "cutoffBlock": 124815050,
          "endUnix": 1786000600,
          "label": "30d",
          "observedDurationSeconds": 40017,
          "startUnix": 1785960583
        }
      },
      {
        "agentId": "97:registry:1809",
        "agentKey": "97-1809",
        "factors": {
          "availability": 1,
          "price": 0,
          "reliability": 1,
          "suitability": 1,
          "verifiedPerformance": 1
        },
        "firstPartyFallback": true,
        "insufficientHistory": true,
        "label": "Atelo Reference Agent (Atelo-owned first-party)",
        "materialFactors": [
          "grid mean_realized_slippage_bps=0bps over 1 VERIFIED job(s) (first-party reference)",
          "suitability=1, price=0, availability=1, reliability=1",
          "first-party fallback: labeled, and not counted toward third-party marketplace diversity",
          "insufficient history: observed 39576s (< 30d window); testnet epoch capped, not presented as a full-window figure"
        ],
        "sampleCount": 1,
        "score": 0.85,
        "thirdParty": false,
        "verifiedPerformanceProvenance": "first-party",
        "window": {
          "cutoffBlock": 124815212,
          "endUnix": 1786000600,
          "label": "30d",
          "observedDurationSeconds": 39576,
          "startUnix": 1785961024
        }
      },
      {
        "agentId": "97:registry:2300",
        "agentKey": "97-2300",
        "factors": {
          "availability": 1,
          "price": 1,
          "reliability": 0,
          "suitability": 0.5,
          "verifiedPerformance": 0
        },
        "firstPartyFallback": false,
        "insufficientHistory": true,
        "label": "ThirdParty Grid Agent (unverified metric)",
        "materialFactors": [
          "no VERIFIED grid performance in window (1 job(s) present but UNVERIFIED)",
          "suitability=0.5, price=1, availability=1, reliability=0",
          "insufficient history: observed 43017s (< 30d window); testnet epoch capped, not presented as a full-window figure"
        ],
        "sampleCount": 0,
        "score": 0.4,
        "thirdParty": true,
        "verifiedPerformanceProvenance": "none",
        "window": {
          "cutoffBlock": 124814050,
          "endUnix": 1786000600,
          "label": "30d",
          "observedDurationSeconds": 43017,
          "startUnix": 1785957583
        }
      },
      {
        "agentId": "97:registry:2400",
        "agentKey": "97-2400",
        "factors": {
          "availability": 0,
          "price": 0.8,
          "reliability": 0,
          "suitability": 0.5,
          "verifiedPerformance": 0
        },
        "firstPartyFallback": false,
        "insufficientHistory": true,
        "label": "ThirdParty Grid Agent (no attributable history)",
        "materialFactors": [
          "no attributable grid history — verified-performance factor is 0",
          "suitability=0.5, price=0.8, availability=0, reliability=0"
        ],
        "sampleCount": 0,
        "score": 0.22,
        "thirdParty": true,
        "verifiedPerformanceProvenance": "none",
        "window": {
          "cutoffBlock": null,
          "endUnix": 1786000600,
          "label": "30d",
          "observedDurationSeconds": 0,
          "startUnix": 1786000600
        }
      }
    ],
    "rankedAtBlock": 124828300,
    "sampleCountTotal": 2,
    "scoreVersion": "atelo-rank/1",
    "task": {
      "category": "grid",
      "network": "bsc-testnet"
    },
    "window": {
      "cutoffBlock": 124815212,
      "endUnix": 1786000600,
      "label": "30d",
      "startUnix": 1785957583
    }
  },
  "rebalancing": {
    "excluded": [
      {
        "key": "97-2200",
        "reason": "category mismatch: declares [grid], task needs rebalancing"
      },
      {
        "key": "97-2300",
        "reason": "category mismatch: declares [grid], task needs rebalancing"
      },
      {
        "key": "97-2400",
        "reason": "category mismatch: declares [grid], task needs rebalancing"
      },
      {
        "key": "97-2500",
        "reason": "category mismatch: declares [grid], task needs rebalancing"
      }
    ],
    "insufficientHistoryWarning": "testnet epoch policy: history capped at \"since first observed, capped at 30 days\"; some agents have less than a full 30d window and are labeled insufficientHistory — short histories are never reported as full-30d figures",
    "observedDurationSeconds": 17265,
    "ranked": [
      {
        "agentId": "97:registry:1809",
        "agentKey": "97-1809",
        "factors": {
          "availability": 1,
          "price": 1,
          "reliability": 1,
          "suitability": 1,
          "verifiedPerformance": 1
        },
        "firstPartyFallback": true,
        "insufficientHistory": true,
        "label": "Atelo Reference Agent (Atelo-owned first-party)",
        "materialFactors": [
          "rebalancing in_range_rate=1rate over 1 VERIFIED job(s) (first-party reference)",
          "suitability=1, price=1, availability=1, reliability=1",
          "first-party fallback: labeled, and not counted toward third-party marketplace diversity",
          "insufficient history: observed 17265s (< 30d window); testnet epoch capped, not presented as a full-window figure"
        ],
        "sampleCount": 1,
        "score": 1,
        "thirdParty": false,
        "verifiedPerformanceProvenance": "first-party",
        "window": {
          "cutoffBlock": 124822636,
          "endUnix": 1786000600,
          "label": "30d",
          "observedDurationSeconds": 17265,
          "startUnix": 1785983335
        }
      }
    ],
    "rankedAtBlock": 124828300,
    "sampleCountTotal": 1,
    "scoreVersion": "atelo-rank/1",
    "task": {
      "category": "rebalancing",
      "network": "bsc-testnet"
    },
    "window": {
      "cutoffBlock": 124822636,
      "endUnix": 1786000600,
      "label": "30d",
      "startUnix": 1785983335
    }
  },
  "yield": {
    "excluded": [
      {
        "key": "97-2200",
        "reason": "category mismatch: declares [grid], task needs yield"
      },
      {
        "key": "97-2300",
        "reason": "category mismatch: declares [grid], task needs yield"
      },
      {
        "key": "97-2400",
        "reason": "category mismatch: declares [grid], task needs yield"
      },
      {
        "key": "97-2500",
        "reason": "category mismatch: declares [grid], task needs yield"
      }
    ],
    "insufficientHistoryWarning": "testnet epoch policy: history capped at \"since first observed, capped at 30 days\"; some agents have less than a full 30d window and are labeled insufficientHistory — short histories are never reported as full-30d figures",
    "observedDurationSeconds": 8376,
    "ranked": [
      {
        "agentId": "97:registry:1809",
        "agentKey": "97-1809",
        "factors": {
          "availability": 1,
          "price": 1,
          "reliability": 1,
          "suitability": 0.5,
          "verifiedPerformance": 0
        },
        "firstPartyFallback": true,
        "insufficientHistory": true,
        "label": "Atelo Reference Agent (Atelo-owned first-party)",
        "materialFactors": [
          "no VERIFIED yield performance in window (1 job(s) present but UNVERIFIED)",
          "suitability=0.5, price=1, availability=1, reliability=1",
          "first-party fallback: labeled, and not counted toward third-party marketplace diversity",
          "insufficient history: observed 8376s (< 30d window); testnet epoch capped, not presented as a full-window figure"
        ],
        "sampleCount": 0,
        "score": 0.5,
        "thirdParty": false,
        "verifiedPerformanceProvenance": "none",
        "window": {
          "cutoffBlock": 124825598,
          "endUnix": 1786000600,
          "label": "30d",
          "observedDurationSeconds": 8376,
          "startUnix": 1785992224
        }
      }
    ],
    "rankedAtBlock": 124828300,
    "sampleCountTotal": 0,
    "scoreVersion": "atelo-rank/1",
    "task": {
      "category": "yield",
      "network": "bsc-testnet"
    },
    "window": {
      "cutoffBlock": 124825598,
      "endUnix": 1786000600,
      "label": "30d",
      "startUnix": 1785992224
    }
  },
  "health": {
    "excluded": [
      {
        "key": "97-2200",
        "reason": "category mismatch: declares [grid], task needs health"
      },
      {
        "key": "97-2300",
        "reason": "category mismatch: declares [grid], task needs health"
      },
      {
        "key": "97-2400",
        "reason": "category mismatch: declares [grid], task needs health"
      },
      {
        "key": "97-2500",
        "reason": "category mismatch: declares [grid], task needs health"
      }
    ],
    "insufficientHistoryWarning": "testnet epoch policy: history capped at \"since first observed, capped at 30 days\"; some agents have less than a full 30d window and are labeled insufficientHistory — short histories are never reported as full-30d figures",
    "observedDurationSeconds": 600,
    "ranked": [
      {
        "agentId": "97:registry:1809",
        "agentKey": "97-1809",
        "factors": {
          "availability": 1,
          "price": 1,
          "reliability": 1,
          "suitability": 1,
          "verifiedPerformance": 1
        },
        "firstPartyFallback": true,
        "insufficientHistory": true,
        "label": "Atelo Reference Agent (Atelo-owned first-party)",
        "materialFactors": [
          "health mean_health_factor_improvement=7.499999hf over 1 VERIFIED job(s) (first-party reference)",
          "suitability=1, price=1, availability=1, reliability=1",
          "first-party fallback: labeled, and not counted toward third-party marketplace diversity",
          "insufficient history: observed 600s (< 30d window); testnet epoch capped, not presented as a full-window figure"
        ],
        "sampleCount": 1,
        "score": 1,
        "thirdParty": false,
        "verifiedPerformanceProvenance": "first-party",
        "window": {
          "cutoffBlock": 124828183,
          "endUnix": 1786000600,
          "label": "30d",
          "observedDurationSeconds": 600,
          "startUnix": 1786000000
        }
      }
    ],
    "rankedAtBlock": 124828300,
    "sampleCountTotal": 1,
    "scoreVersion": "atelo-rank/1",
    "task": {
      "category": "health",
      "network": "bsc-testnet"
    },
    "window": {
      "cutoffBlock": 124828183,
      "endUnix": 1786000600,
      "label": "30d",
      "startUnix": 1786000000
    }
  }
};

export const rankings: Record<Category, RawRanking> = data;
