import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(scriptDir, "../../..");
const artifactsDir = join(repoRoot, "artifacts");
const outDir = join(scriptDir, "..", "src", "data");

const BANNER = "// GENERATED by packages/core/scripts/gen-data.mjs — do not edit by hand.";

function readJson(relative) {
  return JSON.parse(readFileSync(join(artifactsDir, relative), "utf8"));
}

function readByPrefix(dirRelative, prefix) {
  const dir = join(artifactsDir, dirRelative);
  const match = readdirSync(dir)
    .filter((f) => f.startsWith(prefix) && f.endsWith(".json"))
    .sort()
    .pop();
  if (!match) throw new Error(`No artifact matching ${dirRelative}/${prefix}*.json`);
  return JSON.parse(readFileSync(join(dir, match), "utf8"));
}

function listJson(dirRelative) {
  return readdirSync(join(artifactsDir, dirRelative))
    .filter((f) => f.endsWith(".json"))
    .sort();
}

function emit(fileName, header, body) {
  writeFileSync(join(outDir, fileName), `${BANNER}\n${header}\n\n${body}\n`);
}

function lit(value) {
  return JSON.stringify(value, null, 2);
}

mkdirSync(outDir, { recursive: true });

const summary = readJson("phase-01/qualification-summary.json");
const reportFiles = listJson("phase-01/qualification-reports");
const reports = reportFiles.map((f) => readJson(`phase-01/qualification-reports/${f}`));

emit(
  "qualification.ts",
  'import type { RawSummary, RawReport } from "../raw";',
  `const summary = ${lit(summary)};\n\nexport const qualificationSummary: RawSummary = summary;\n\nconst reports = ${lit(reports)};\n\nexport const qualificationReports: RawReport[] = reports;`
);

const rankingFiles = {
  grid: "phase-05/ranking-grid.json",
  rebalancing: "phase-05/ranking-rebalancing.json",
  yield: "phase-05/ranking-yield.json",
  health: "phase-05/ranking-health.json"
};
const rankings = Object.fromEntries(
  Object.entries(rankingFiles).map(([cat, rel]) => [cat, readJson(rel)])
);

emit(
  "rankings.ts",
  'import type { Category } from "../types";\nimport type { RawRanking } from "../raw";',
  `const data = ${lit(rankings)};\n\nexport const rankings: Record<Category, RawRanking> = data;`
);

const lineageIds = ["501", "503", "504", "505"];
const lineageRecords = Object.fromEntries(
  lineageIds.map((id) => [id, readJson(`phase-04/lineage/${id}.json`)])
);
const greenfield = readByPrefix("phase-04", "greenfield-upload-");

emit(
  "lineage.ts",
  'import type { RawLineage, RawGreenfield } from "../raw";',
  `const records = ${lit(lineageRecords)};\n\nexport const lineageRecords: Record<string, RawLineage> = records;\n\nconst greenfieldData = ${lit(greenfield)};\n\nexport const greenfield: RawGreenfield = greenfieldData;`
);

const lifecyclePrefix = {
  grid: "lifecycle-grid",
  rebalancing: "lifecycle-rebalancing",
  yield: "lifecycle-yield",
  health: "lifecycle-venus"
};
const lifecycles = Object.fromEntries(
  Object.entries(lifecyclePrefix).map(([cat, prefix]) => [cat, readByPrefix("phase-03", prefix)])
);

emit(
  "jobs.ts",
  'import type { Category } from "../types";\nimport type { RawLifecycle } from "../raw";',
  `const data = ${lit(lifecycles)};\n\nexport const lifecycles: Record<Category, RawLifecycle> = data;`
);

console.log(
  `gen-data: ${reports.length} reports, ${Object.keys(rankings).length} rankings, ${lineageIds.length} lineage records, ${Object.keys(lifecycles).length} lifecycles`
);
